Release 0.8.0 (#34) (#35)
### Features

* add AWS SQS ReceiveMessage latency histogram
* Add command line flags for parameters
* Add configurable thread count for realtime updater
* Add functional test
* Adding e2e latency measurement for realtime updates
* Allow specifying explicit histogram bucket boundaries
* Allow the blob_storage_util cp command to work with local files.
* Allow the DeltaFileRecordChangeNotifier to read local files as well as from S3
* Batch delete SQS messages
* Build delta files from csv
* clean up realtime queues
* Configure AWS hosted Prometheus.
* Disable the use of exceptions
* Enhance/Simplify local export of telemetry with OTLP.
* Functional testing of local server with delta files
* make AwsSnsSqsManager thread safe
* Make the blob_storage_change_watcher tool work for local files
* Make the blob_storage_util cat and rm commands work for local files
* Make the blob_storage_util ls command work for local files and refactor out common parts from the AWS binary
* Make the delta_file_watcher tool work for local files
* Move the platform specific server configuration logic to a separate file
* multi-threaded realtime notifier
* realtime tester in a container
* Reuse SQS client
* Speed up test updates publisher
* Tools for generating and inserting realtime test data.
* Upgrade build-system to release-0.18.0
* Upgrade build-system to release-0.20.0
* Upgrade debian runtime images to 15 Feb 2023
* Upgrade to build-system 0.17.0
* Use a PlatformInitializer so the data_cli will compile for --platform=local

### Bug Fixes

* Add ability to interrupt a SleepFor Duration.
* Add minimum shard size threshold for concurrent reader.
* Launch Envoy first before all other processes.
* Make MetricsRecorder a shared global instance.
* Only run functional tests against local server
* Remove functionaltest/run-server, update docs accordingly
* Remove submodule section from docs
* Run server in background, and reduce noise
* Run server using delta files in run-server-docker
* Update generate_load_test_data to use bazel-debian
* Use symlink for identical test replies
* Use VLOG for concurrent reader debugging logs.
* Wait for envoy to respond before launching enclave service.

### Documentation

* Add a playbook template for new alerts
* Add description for backup_poll_frequency_secs
* Add docs about how to run the server locally
* fix /tmp/deltas discrepancy
* remove obsolete service
* Updating instructions on how to copy `eif` manually.

### Terraform

* Convert tfvar files to json
* Support Prometheus service running in a different region

Change-Id: I67f31c6d05015b4674e1a9600ce7f190af46e390
Bug: 275543946
GitOrigin-RevId: 41c735e45b2e5f6553caef9584a670d8a83a095b

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/builders/tests/run-tests b/builders/tests/run-tests
--- a/builders/tests/run-tests
+++ b/builders/tests/run-tests
@@ -42,19 +42,29 @@ function usage() {
   cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
-    --fast       Only generate hashes directly rather than also using cbuild
+    --image <name>  Run tests only for specified image
+    --fast          Only generate hashes directly rather than also using cbuild
+    --verbose       Produce verbose output
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
 
-declare -i DIRECT_ONLY=0
+declare -i FAST=0
 declare -i VERBOSE=0
+declare IMAGE
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
+    --image)
+      IMAGE="$2"
+      if [[ -z ${IMAGE} ]]; then
+        usage
+      fi
+      shift 2
+      ;;
     --fast)
-      DIRECT_ONLY=1
+      FAST=1
       shift
       ;;
     --verbose)
@@ -74,21 +84,87 @@ readonly TESTS_DIR
 readonly TOOLS_DIR="${TESTS_DIR}"/../tools
 readonly HASHES_DIR="${TESTS_DIR}"/data/hashes
 readonly IMAGES_DIR="${TESTS_DIR}"/../images
-IMAGE_LIST="$(get_image_list "${IMAGES_DIR}")"
+if [[ -n ${IMAGE} ]]; then
+  IMAGE_LIST="${IMAGE}"
+else
+  IMAGE_LIST="$(get_image_list "${IMAGES_DIR}")"
+fi
 readonly IMAGE_LIST
 declare -i RETCODE=0
 
-TMP_HASHES_DIR1=$(mktemp --directory)
+function cli_tests_test-tools() {
+  declare -r _image="$1"
+  if [[ ${FAST} -eq 1 ]] || [[ ${_image} != test-tools ]]; then
+    return
+  fi
+  declare -a -r TOOLS=(
+    "${TOOLS_DIR}/curl --version"
+    "${TOOLS_DIR}/ghz --version"
+    "${TOOLS_DIR}/ab -V"
+    "${TOOLS_DIR}/cassowary --version"
+    "${TOOLS_DIR}/grpcurl -version"
+    "${TOOLS_DIR}/h2load --version"
+    "${TOOLS_DIR}/hadolint --version"
+    "${TOOLS_DIR}/jq --version"
+  )
+  printf "Testing test CLI tool wrappers\n"
+  for tool_cmd in "${TOOLS[@]}"; do
+    printf "  %s\n" "${tool_cmd}"
+    ${tool_cmd} &>/dev/null
+  done
+}
+
+function cli_tests_utils() {
+  declare -r _image="$1"
+  if [[ ${FAST} -eq 1 ]] || [[ ${_image} != utils ]]; then
+    return
+  fi
+  declare -a -r TOOLS=(
+    "${TOOLS_DIR}/unzip -h"
+    "${TOOLS_DIR}/zip -h"
+  )
+  printf "Testing utils CLI tool wrappers\n"
+  for tool_cmd in "${TOOLS[@]}"; do
+    printf "  %s\n" "${tool_cmd}"
+    ${tool_cmd} &>/dev/null
+  done
+}
+
+function cli_tests_release() {
+  declare -r _image="$1"
+  if [[ ${FAST} -eq 1 ]] || [[ ${_image} != release ]]; then
+    return
+  fi
+  declare -a -r TOOLS=(
+    "${TOOLS_DIR}/buildozer -version"
+  )
+  printf "Testing release CLI tool wrappers\n"
+  for tool_cmd in "${TOOLS[@]}"; do
+    printf "  %s\n" "${tool_cmd}"
+    ${tool_cmd} &>/dev/null
+  done
+}
+
+function create_temp_hash_dir() {
+  local -r DIR=$(mktemp --directory)
+  cp "${HASHES_DIR}"/* "${DIR}"
+  printf "%s" "${DIR}"
+}
+
+TMP_HASHES_DIR1=$(create_temp_hash_dir)
 
 # warning when running inside a docker container
 if [[ -f /.dockerenv ]]; then
   printf "warning: Executing within docker container, which obviates testing in a non-docker environment\n" &>/dev/stderr
 fi
 printf "Generating image hashes (direct mode)\n"
-declare -r GET_BUILDER_IMAGE_ARGS="--no-build --sha-only"
+declare -a -r GET_BUILDER_IMAGE_ARGS=(
+  --no-build
+  --sha-only
+)
 for img in ${IMAGE_LIST}; do
   # shellcheck disable=SC2086
-  if ! "${TOOLS_DIR}"/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS} --image ${img} >"${TMP_HASHES_DIR1}/${img}"; then
+  if ! "${TOOLS_DIR}"/get-builder-image-tagged "${GET_BUILDER_IMAGE_ARGS[@]}" --image ${img} >"${TMP_HASHES_DIR1}/${img}"; then
     printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
     RETCODE+=1
   fi
@@ -108,15 +184,15 @@ else
   printf "hashes unchanged\n"
 fi
 
-if [[ ${DIRECT_ONLY} -eq 1 ]]; then
+if [[ ${FAST} -eq 1 ]]; then
   exit ${RETCODE}
 fi
 
-TMP_HASHES_DIR2=$(mktemp --directory)
+TMP_HASHES_DIR2=$(create_temp_hash_dir)
 
 printf "Generating image hashes (cbuild mode)\n"
 for img in ${IMAGE_LIST}; do
-  if ! "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS} --image ${img}" >"${TMP_HASHES_DIR2}/${img}"; then
+  if ! "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS[*]} --image ${img}" >"${TMP_HASHES_DIR2}/${img}"; then
     printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
     RETCODE+=1
   fi
@@ -134,4 +210,23 @@ if [[ -n $MODE_MISMATCH ]]; then
 else
   printf "hashes unchanged\n"
 fi
+
+# CLI tests
+
+for img in ${IMAGE_LIST}; do
+  cli_tests_test-tools "${img}"
+  cli_tests_utils "${img}"
+  cli_tests_release "${img}"
+done
+
+printf "test for error in direct execution of underlying wrapper scripts\n"
+for tool in test-tool utils-tool; do
+  printf "  %s: " "${tool}"
+  if ! "${TOOLS_DIR}"/${tool} &>/dev/null; then
+    printf "ok\n"
+  else
+    printf "failed to exit non-zero\n"
+  fi
+done
+
 exit ${RETCODE}
