Release 0.11.0 (2023-07-11) (#40)
### Features

* [Breaking change] Use UserDefinedFunctionsConfig instead of KVs for loading UDFs.
* [Sharding] Add hpke for s2s communication
* [Sharding] Allow for partial data lookups
* [Sharding] Making downstream requests in parallel
* Add bazel build flag --announce_rc
* Add bool parameter to allow routing V1 requests through V2.
* Add buf format pre-commit hook
* Add build time directive for reentrant parser.
* Add functions to retrieve instance information.
* Add internal run query client and server.
* Add JS hook for set query.
* Add lookup client and server for communication with shards
* Add MessageQueue for the request simulation system
* Add query grammar and interface for set queries.
* Add rate limiter for the request simulation system
* Add second map to store key value set and add set value update interfaces
* Add shard metadata for supporting sharded files
* Add simple microbenchmarks for key value cache
* Add UDF support for format data command.
* Add unit tests for query lexer.
* Adding cluster mappings manager
* Adding padding
* Apply custom lockings on the cache
* Connect InternalRunQuery to the parser
* Extend and simplify collect-logs to capture test outputs
* Extend use of scp deps via data-plane-shared repo
* Implement shard manager
* Move sharding function to public so it's available for file sharding
* Register a logging hook with the UDF.
* Register run query hook with udf framework.
* Sharding - realtime updates
* Sharding read flow fixes
* Simplify work done in set operations. Set operations can be passed by
* Snapshot files support UDF configs.
* Support reading and writing set queries to data files.
* Support reading and writing set values for csv files
* Support reading/writing DataRecords. Requires new DELTA format.
* Support writing sharded files
* Update data_loading.fb to support UDF code updates.
* Update pre-commit hook versions
* Update shard manager mappings continuously
* Upgrade build-system to release-0.28.0
* Upgrade build-system to v0.30.1
* Upgrade scp to 0.72.0
* Use Unix domain socket for internal lookup server.
* Utilize AWS deps via data-plane-shared repo

### Bug Fixes

* Add internal lookup client deadline.
* Catch error if insufficient args specified
* Fix aggregation logic for set values.
* Fix ASAN potential deadlock errors in key_value_cache_test
* Proper memory management of callback hook wrappers.
* Specify 2 workers for UDF execution.
* Upgrade pre-commit hooks
* Use shared pointer for UDF absl::Notification.

### Build Tools: Fixes

* **build:** Add scope-based sections in release notes

### Documentation

* Add docs for data loading capabilities
* Add explanation that access control is managed by IAM for writes.
* Point readme to a new sharding public explainer

Bug: 290798418
Change-Id: I691da695f5727a8517ed3e9f18a3a2d8c5b9e0bf
GitOrigin-RevId: 5958051464911b6da60c38bc2a83c3451adadf42

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/builders/tests/run-tests b/builders/tests/run-tests
--- a/builders/tests/run-tests
+++ b/builders/tests/run-tests
@@ -21,7 +21,7 @@ set -o errexit
 
 trap _cleanup EXIT
 function _cleanup() {
-  declare -r -i STATUS=$?
+  local -r -i STATUS=$?
   if [[ -d ${TMP_HASHES_DIR1} ]]; then
     rm -rf "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}"
   fi
@@ -33,8 +33,9 @@ function _cleanup() {
 }
 
 function get_image_list() {
-  declare -r _images_dir="$1"
-  find "${_images_dir}" -maxdepth 1 -mindepth 1 -type d -printf "%P\n" | sort
+  local -r _images_dir="$1"
+  find "${_images_dir}" -maxdepth 1 -mindepth 1 -type d -printf "%P\n" \
+    | sort
 }
 
 function usage() {
@@ -44,6 +45,7 @@ usage:
   $0 <options>
     --image <name>  Run tests only for specified image
     --fast          Only generate hashes directly rather than also using cbuild
+    --build-images  Build the images
     --verbose       Produce verbose output
 USAGE
   # shellcheck disable=SC2086
@@ -52,6 +54,7 @@ USAGE
 
 declare -i FAST=0
 declare -i VERBOSE=0
+declare -i BUILD_IMAGES=0
 declare IMAGE
 
 while [[ $# -gt 0 ]]; do
@@ -61,10 +64,14 @@ while [[ $# -gt 0 ]]; do
       if [[ -z ${IMAGE} ]]; then
         usage
       fi
-      shift 2
+      shift 2 || usage
       ;;
     --fast)
       FAST=1
+      shift
+      ;;
+    --build-images)
+      BUILD_IMAGES=1
       shift
       ;;
     --verbose)
@@ -116,7 +123,7 @@ function cli_tests_test-tools() {
 
 function cli_tests_misc() {
   declare -a -r TOOLS=(
-    "${TOOLS_DIR}/aws-cli --help"
+    "${TOOLS_DIR}/aws-cli help"
     "${TOOLS_DIR}/awscurl --help"
   )
   printf "Testing utils CLI tool wrappers\n"
@@ -158,70 +165,82 @@ function cli_tests_release() {
 }
 
 function create_temp_hash_dir() {
-  declare -r DIR=$(mktemp --directory)
+  local -r DIR="$(mktemp --directory)"
   cp "${HASHES_DIR}"/* "${DIR}"
   printf "%s" "${DIR}"
 }
-
-TMP_HASHES_DIR1=$(create_temp_hash_dir)
 
 # warning when running inside a docker container
 if [[ -f /.dockerenv ]]; then
   printf "warning: Executing within docker container, which obviates testing in a non-docker environment\n" &>/dev/stderr
 fi
-printf "Generating image hashes (direct mode)\n"
-declare -a -r GET_BUILDER_IMAGE_ARGS=(
-  --no-build
+
+declare -a GET_BUILDER_IMAGE_ARGS=(
   --sha-only
 )
-for img in ${IMAGE_LIST}; do
-  # shellcheck disable=SC2086
-  if ! "${TOOLS_DIR}"/get-builder-image-tagged "${GET_BUILDER_IMAGE_ARGS[@]}" --image ${img} >"${TMP_HASHES_DIR1}/${img}"; then
-    printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
-    RETCODE+=1
-  fi
-done
-
-BASELINE_UPDATES="$(diff --brief "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true)"
-readonly BASELINE_UPDATES
-if [[ -n $BASELINE_UPDATES ]]; then
-  # shellcheck disable=SC2086
-  printf "detected shift in baseline files:\n%s\n" "${BASELINE_UPDATES}"
-  if [[ ${VERBOSE} -eq 1 ]]; then
-    diff "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true
-  fi
-  cp --force "${TMP_HASHES_DIR1}"/* "${HASHES_DIR}"
-  RETCODE+=10
-else
-  printf "hashes unchanged\n"
+if [[ ${BUILD_IMAGES} -eq 0 ]]; then
+  GET_BUILDER_IMAGE_ARGS+=(--no-build)
 fi
+
+function generate_hashes_direct() {
+  TMP_HASHES_DIR1=$(create_temp_hash_dir)
+  printf "Generating image hashes (direct mode)\n"
+
+  for img in ${IMAGE_LIST}; do
+    # shellcheck disable=SC2086
+    if ! "${TOOLS_DIR}"/get-builder-image-tagged "${GET_BUILDER_IMAGE_ARGS[@]}" --image ${img} >"${TMP_HASHES_DIR1}/${img}"; then
+      printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
+      RETCODE+=1
+    fi
+  done
+
+  BASELINE_UPDATES="$(diff --brief "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true)"
+  readonly BASELINE_UPDATES
+  if [[ -n $BASELINE_UPDATES ]]; then
+    # shellcheck disable=SC2086
+    printf "detected shift in baseline files:\n%s\n" "${BASELINE_UPDATES}"
+    if [[ ${VERBOSE} -eq 1 ]]; then
+      diff "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true
+    fi
+    cp --force "${TMP_HASHES_DIR1}"/* "${HASHES_DIR}"
+    RETCODE+=10
+  else
+    printf "hashes unchanged\n"
+  fi
+}
+
+function generate_hashes_cbuild() {
+  TMP_HASHES_DIR2=$(create_temp_hash_dir)
+
+  printf "Generating image hashes (cbuild mode)\n"
+  for img in ${IMAGE_LIST}; do
+    if ! "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS[*]} --image ${img}" >"${TMP_HASHES_DIR2}/${img}"; then
+      printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
+      RETCODE+=1
+    fi
+  done
+
+  MODE_MISMATCH="$(diff --brief "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true)"
+  readonly MODE_MISMATCH
+  if [[ -n $MODE_MISMATCH ]]; then
+    # shellcheck disable=SC2086
+    printf "Error: mismatch between direct and cbuild modes\n%s" "${MODE_MISMATCH}" &>/dev/stderr
+    if [[ ${VERBOSE} -eq 1 ]]; then
+      diff "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true
+    fi
+    RETCODE+=100
+  else
+    printf "hashes unchanged\n"
+  fi
+}
+
+generate_hashes_direct
 
 if [[ ${FAST} -eq 1 ]]; then
   exit ${RETCODE}
 fi
 
-TMP_HASHES_DIR2=$(create_temp_hash_dir)
-
-printf "Generating image hashes (cbuild mode)\n"
-for img in ${IMAGE_LIST}; do
-  if ! "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS[*]} --image ${img}" >"${TMP_HASHES_DIR2}/${img}"; then
-    printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
-    RETCODE+=1
-  fi
-done
-
-MODE_MISMATCH="$(diff --brief "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true)"
-readonly MODE_MISMATCH
-if [[ -n $MODE_MISMATCH ]]; then
-  # shellcheck disable=SC2086
-  printf "Error: mismatch between direct and cbuild modes\n%s" "${MODE_MISMATCH}" &>/dev/stderr
-  if [[ ${VERBOSE} -eq 1 ]]; then
-    diff "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true
-  fi
-  RETCODE+=100
-else
-  printf "hashes unchanged\n"
-fi
+generate_hashes_cbuild
 
 # CLI tests
 
