Release 0.7.0 (#30) (#31)
### Features

* Add --platform flag to build_and_test_all_in_docker
* Add a concurrent record reader for data files.
* Add a helper service for protocol testing
* Add a stub class for reading local blob files
* add automated PCR0 updates to kokoro continuous
* Add base streambuf with seeking support for reading blobs.
* Add delta writer and custom audience data parser
* add github personal access token validation for release scripts
* Add instance id to metrics.
* Add seeking to S3 blob reader.
* Add support for Zipkin exports for local builds.
* Add terraform logic to create SNS for real time updates
* Check timestamps for cache update
* Implement BinaryHTTP version of V2 API
* Implement delta file record change notifier to retrieve high priority updates
* Implement test OHTTP V2 query handling
* Integrating high priority updates in data server
* Memory cleanup for delete timestamps in the cache
* Record metrics for all RetryUntilOk events.  Export them to stdout or
* Upgrade black to 23.1.0
* Upgrade to build-system 0.13.0
* Upgrade to build-system 0.14.0
* Upgrade to build-system 0.16.0
* Use concurrent reader for reading snapshot and delta files.

### Bug Fixes

* Add docker compose config for testing locally.
* add empty bug id to automated PCR0 CL
* Add unit test for delta file backup poll.  Fix bug where we can't
* Don't ListBlobs to poll Delta files on notifications that don't
* Don't use default number of cores for small test files.
* fetch git remote for automated pcr0 updates
* Fix typos and remove unreachable branches.
* flaky delta_file_notifier test.
* Listing non-delta files from bucket shouldn't cause state change.
* Only read the most recent snapshot file.
* path for local envoy
* Prefer github release artifacts over archive artifacts
* remove duplicate open telemetry entry.
* remove spaces from automated PCR0 CL commit footer
* Switch jaeger over to using OTLP directly.  Jaeger otel component is
* Upgrade to rules_buf 0.1.1
* Uprev Otel to pull in semantic resource convensions.  Use them
* Use shared libraries for proxy

### Build System

* Hide build stdout/stderr for third_party

### Documentation

* Add docs for data loading library.

Change-Id: I37444494693c1ba3f3edfa2760ae48bf415e88de
Bug: b/269120926
GitOrigin-RevId: 789c517d33605180cacfe578e8747e7129a0f092

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/builders/tests/run-tests b/builders/tests/run-tests
--- a/builders/tests/run-tests
+++ b/builders/tests/run-tests
@@ -22,11 +22,12 @@ set -o errexit
 trap _cleanup EXIT
 function _cleanup() {
   declare -r -i STATUS=$?
-  if [[ -d ${TMP_HASHES_DIR} ]]; then
-    rm -rf "${TMP_HASHES_DIR}"
+  if [[ -d ${TMP_HASHES_DIR1} ]]; then
+    rm -rf "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}"
   fi
   if [[ ${STATUS} -ne 0 ]]; then
-    printf "Error: run-tests status code: %d\n" "${STATUS}" &>/dev/stderr
+    printf "Error: run-tests status code: %d\n" "${STATUS}"
+    sleep 5s
   fi
   exit ${STATUS}
 }
@@ -40,14 +41,26 @@ function usage() {
   declare -r -i exitval=${1-1}
   cat &>/dev/stderr <<USAGE
 usage:
-  $0
+  $0 <options>
+    --fast       Only generate hashes directly rather than also using cbuild
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
 
+declare -i DIRECT_ONLY=0
+declare -i VERBOSE=0
+
 while [[ $# -gt 0 ]]; do
   case "$1" in
+    --fast)
+      DIRECT_ONLY=1
+      shift
+      ;;
+    --verbose)
+      VERBOSE=1
+      shift
+      ;;
     -h | --help) usage 0 ;;
     *)
       printf "unrecognized arg: %s\n" "$1"
@@ -63,30 +76,62 @@ readonly HASHES_DIR="${TESTS_DIR}"/data/hashes
 readonly IMAGES_DIR="${TESTS_DIR}"/../images
 IMAGE_LIST="$(get_image_list "${IMAGES_DIR}")"
 readonly IMAGE_LIST
+declare -i RETCODE=0
+
+TMP_HASHES_DIR1=$(mktemp --directory)
 
 # warning when running inside a docker container
 if [[ -f /.dockerenv ]]; then
   printf "warning: Executing within docker container, which obviates testing in a non-docker environment\n" &>/dev/stderr
 fi
 printf "Generating image hashes (direct mode)\n"
+declare -r GET_BUILDER_IMAGE_ARGS="--no-build --sha-only"
 for img in ${IMAGE_LIST}; do
-  "${TOOLS_DIR}"/get-builder-image-tagged --no-build --image "${img}" >"${HASHES_DIR}/${img}"
+  # shellcheck disable=SC2086
+  if ! "${TOOLS_DIR}"/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS} --image ${img} >"${TMP_HASHES_DIR1}/${img}"; then
+    printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
+    RETCODE+=1
+  fi
 done
 
-BASELINE_UPDATES="$(git diff --name-only "${HASHES_DIR}")"
+BASELINE_UPDATES="$(diff --brief "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true)"
+readonly BASELINE_UPDATES
 if [[ -n $BASELINE_UPDATES ]]; then
   # shellcheck disable=SC2086
-  printf "detected shift in baseline files: %s\n" ${BASELINE_UPDATES}
+  printf "detected shift in baseline files:\n%s\n" "${BASELINE_UPDATES}"
+  if [[ ${VERBOSE} -eq 1 ]]; then
+    diff "${HASHES_DIR}" "${TMP_HASHES_DIR1}" || true
+  fi
+  cp --force "${TMP_HASHES_DIR1}"/* "${HASHES_DIR}"
+  RETCODE+=10
+else
+  printf "hashes unchanged\n"
 fi
 
-TMP_HASHES_DIR=$(mktemp -d)
+if [[ ${DIRECT_ONLY} -eq 1 ]]; then
+  exit ${RETCODE}
+fi
+
+TMP_HASHES_DIR2=$(mktemp --directory)
 
 printf "Generating image hashes (cbuild mode)\n"
 for img in ${IMAGE_LIST}; do
-  "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged --image ${img} --no-build" >"${TMP_HASHES_DIR}/${img}"
+  if ! "${TOOLS_DIR}"/cbuild --image build-debian --cmd "tools/get-builder-image-tagged ${GET_BUILDER_IMAGE_ARGS} --image ${img}" >"${TMP_HASHES_DIR2}/${img}"; then
+    printf "Error generating image hash: %s\n" "${img}" &>/dev/stderr
+    RETCODE+=1
+  fi
 done
 
-if ! diff --recursive "${HASHES_DIR}" "${TMP_HASHES_DIR}"; then
-  printf "error: mismatch between direct and cbuild mode\n" &>/dev/stderr
-  exit 1
+MODE_MISMATCH="$(diff --brief "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true)"
+readonly MODE_MISMATCH
+if [[ -n $MODE_MISMATCH ]]; then
+  # shellcheck disable=SC2086
+  printf "Error: mismatch between direct and cbuild modes\n%s" "${MODE_MISMATCH}" &>/dev/stderr
+  if [[ ${VERBOSE} -eq 1 ]]; then
+    diff "${TMP_HASHES_DIR1}" "${TMP_HASHES_DIR2}" || true
+  fi
+  RETCODE+=100
+else
+  printf "hashes unchanged\n"
 fi
+exit ${RETCODE}
