Release 0.10.0 (2023-05-04) (#38)
### Features

* Add --fast option for running functional tests
* Add a multi-KV SUT
* Add baseline for SSP
* Add bazel macro to generate OpenSSL certificates
* Add brotli compression support
* Add envoy for KV server in baseline SUT
* Add envoy frontend in baseline SUT
* Add optional filename arg to tools/collect-logs
* Add SUT without UDF
* Add terraform support for sharding
* Drop data meant for other shards
* Include tink_cc repository
* Set timestamp for generated delta files for SUTs
* Support selection of single SUT for testing
* Upgrade gRPC to v1.52.1
* Upgrade to functionaltest-system 0.5.1
* Use 443 for http1.1 and 8443 for http2.
* Use scp deps exposed by data-plane-shared-libraries repo
* Use shared control plane skylark functions for transitive dependencies

### Bug Fixes

* Address linter issues in production dir
* Address linter issues in tools
* Avoid running prettier on PCR0 files
* Capture test logs into zip archive
* Collect logs from functional testing
* Configure docker compose to pull images quietly
* Correct container deps in multiple-kv-servers
* Defer to data-plane-shared cpp deps
* Remove exposed ports as not needed within docker network
* Remove unused code in tools/get_workspace_status
* Remove workspace parent dirs from logs archive
* Upgrade pre-commit hooks

### Documentation

* Add Protected Audience API rename banner

Bug: 280464254
Change-Id: I3577b3dd6124c8cad66717b1c43b774e3d445fe5
GitOrigin-RevId: e8331cb873bd61ed708ee1e62fcf108c684e53af

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/testing/functionaltest/run-tests b/testing/functionaltest/run-tests
--- a/testing/functionaltest/run-tests
+++ b/testing/functionaltest/run-tests
@@ -35,26 +35,28 @@ function _cleanup() {
 }
 
 function usage() {
-  declare -r -i exitval=$?
+  declare -r exitval="$1"
   cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
-      --network <name>       docker network name
-      --endpoint <host:port> host:port for service
+      --sut-name <name>      name of SUT (must match directory name within suts path)
+      --fast                 only run a single set of tests per SUT
       --verbose              verbose output
 USAGE
-  exit ${exitval}
+  exit "${exitval}"
 }
+
+declare -i SHORT_CIRCUIT=0
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    --network)
-      DOCKER_NETWORK="$2"
+    --sut-name)
+      SUT_NAME="$2"
       shift 2
       ;;
-    --endpoint)
-      ENDPOINT="$2"
-      shift 2
+    --fast)
+      SHORT_CIRCUIT=1
+      shift
       ;;
     --verbose)
       set -o xtrace
@@ -63,35 +65,39 @@ while [[ $# -gt 0 ]]; do
     -h | --help) usage 0 ;;
     *)
       printf "unrecognized arg: %s\n" "$1"
-      usage
+      usage 1
       ;;
   esac
 done
 
-: "${DOCKER_NETWORK?"--network flag not specified"}"
-: "${ENDPOINT?"--endpoint flag not specified"}"
+: "${SUT_NAME?"--sut-name flag not specified"}"
 
-TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/../../builders/tools
+SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+readonly SCRIPT_DIR
+TOOLS_DIR="${SCRIPT_DIR}"/../../builders/tools
 readonly TOOLS_DIR
-
-declare -a TEST_ARGS=(
-  "--test_env=KVSERVER_ENDPOINT=${ENDPOINT}"
-  "--test_env=TEST_TOOLS_IMAGE=$("${TOOLS_DIR}"/get-builder-image-tagged --image test-tools)"
-)
-
-if [[ -v DOCKER_NETWORK ]]; then
-  TEST_ARGS+=(
-    "--test_env=DOCKER_NETWORK=${DOCKER_NETWORK}"
-  )
+SUTS_DIR="${SCRIPT_DIR}"/suts
+readonly SUTS_DIR
+declare -r SUT_DIR="${SUTS_DIR}/${SUT_NAME}"
+if ! [[ -d ${SUT_DIR} ]]; then
+  printf "SUT directory not found: [%s]\n" "${SUT_DIR}" &>/dev/stderr
+  exit 1
 fi
 
+readonly TOOLS_DIR
+declare -a -r TEST_ARGS=(
+  "--test_env=TEST_TOOLS_IMAGE=$("${TOOLS_DIR}"/get-builder-image-tagged --image test-tools)"
+)
 declare -a -r TESTS=(
-  "//testing/functionaltest/test_cases/grpc:grpcurl_test_suite"
+  "//testing/functionaltest/suts/${SUT_NAME}:grpcurl_test_suite"
 )
 
 # run the tests using bazel, if installed
 if command bazel --help &>/dev/null; then
   bazel test "${TESTS[@]}" "${TEST_ARGS[@]}"
+  if [[ ${SHORT_CIRCUIT} -eq 1 ]]; then
+    exit
+  fi
 fi
 
 # also run the test suites using bazel-debian container
