Add option to iterate through udf deltas and kv deltas to benchmark script.
Bug: b/322982024
Change-Id: I9fe76693ef4391d372ac123a4effefc0e776362f
GitOrigin-RevId: 15b1c2b81067032f9856e1ac236ff2df1ebe4d32

diff --git a/tools/latency_benchmarking/deploy_and_benchmark b/tools/latency_benchmarking/deploy_and_benchmark
--- a/tools/latency_benchmarking/deploy_and_benchmark
+++ b/tools/latency_benchmarking/deploy_and_benchmark
@@ -21,16 +21,27 @@ source ./builders/tools/builder.sh
 
 WORKSPACE="$(git rev-parse --show-toplevel)"
 
-SERVER_WAIT_TIMEOUT="5m"
+# Script input params
+EXTRA_SERVER_WAIT_TIMEOUT="5m"
+MINIMUM_SERVER_WAIT_SECS=60
 NUMBER_OF_LOOKUP_KEYS_LIST="1 10 50 100"
 GHZ_TAGS="{}"
 
+# Additional GHZ tags per deployment/udf
+DEPLOYMENT_GHZ_TAGS="{}"
+UDF_GHZ_TAGS="{}"
+
+# Input to run_benchmark script
+declare RUN_BENCHMARK_ARGS
+
+# Deployment vars
 declare SERVER_ADDRESS
 declare SERVER_ENDPOINT
-declare -a BENCHMARK_CSVS
 
+# CSV I/O
+declare -a BENCHMARK_CSVS
 CSV_OUTPUT="${WORKSPACE}/dist/tools/latency_benchmarking/output/output.csv"
-DOCKER_OUTPUT_CSV="/tmp/latency_benchmarking/output/output.csv"
+DOCKER_OUTPUT_CSV="/tmp/latency_benchmarking/output/deploy_and_benchmark/output.csv"
 readonly DOCKER_OUTPUT_CSV
 
 # run_benchmarks writes output to this directory
@@ -68,14 +79,23 @@ USAGE
   exit ${exitval}
 }
 
-function run_benchmarks() {
-  local -a RUN_BENCHMARK_ARGS=(
+function set_benchmark_args() {
+  SERVER_ADDRESS="lusa.kv-server.privacysandboxdemo.app:8443"
+  local -a RUN_BENCHMARK_GHZ_TAGS
+  RUN_BENCHMARK_GHZ_TAGS=$(jq -s -c 'add' <(echo "${GHZ_TAGS}") \
+    <(echo "${DEPLOYMENT_GHZ_TAGS}") \
+    <(echo "${UDF_GHZ_TAGS}"))
+  RUN_BENCHMARK_ARGS=(
       --number-of-lookup-keys-list "${NUMBER_OF_LOOKUP_KEYS_LIST[@]}"
       --server-address "${SERVER_ADDRESS}"
+      --ghz-tags "${RUN_BENCHMARK_GHZ_TAGS}"
+      --snapshot-dir "${SNAPSHOT_DIR}"
       )
-  if [[ -n "${EXTRA_GHZ_TAGS}" ]]; then
-      RUN_BENCHMARK_ARGS+=(--ghz-tags "${EXTRA_GHZ_TAGS}")
-  fi
+  }
+
+function run_benchmarks() {
+  set_benchmark_args
+  printf "BENCHMARK ARGS: %s\n" "${RUN_BENCHMARK_ARGS[*]}"
 
   local BENCHMARK_OUTPUT
   BENCHMARK_OUTPUT=$(./tools/latency_benchmarking/run_benchmarks "${RUN_BENCHMARK_ARGS[@]}")
@@ -83,7 +103,6 @@ function run_benchmarks() {
     "$(echo "${BENCHMARK_OUTPUT}" | tail -n 1 2>&1 | tee /dev/tty)"
   )
 }
-
 
 function set_server_address() {
   # Build HTTP server endpoint from tf output
@@ -117,16 +136,29 @@ function deploy_and_benchmark() {
   set_server_address "${TF_APPLY_LAST_LINE}"
 
   # Wait for potential instance teardown before periodically checking if server is ready
-  sleep 60
+  sleep "${MINIMUM_SERVER_WAIT_SECS}"
 
   # Wait for server to be up
-  timeout --foreground "${SERVER_WAIT_TIMEOUT}" bash -c \
+  timeout --foreground "${EXTRA_SERVER_WAIT_TIMEOUT}" bash -c \
     "until curl --output /dev/null --silent --fail ${SERVER_ENDPOINT};do sleep 15; done"
   printf "Server ready, running benchmarks\n"
 
-  # TODO: cp SNAPSHOT file to dir
-  run_benchmarks
-  # TODO: Upload UDFs
+  # Iterate through each given UDF
+  # Upload delta file, run benchmarks, then remove it
+  if [[ -d "${UDF_DELTA_DIR}" ]]; then
+    for FILE in "${UDF_DELTA_DIR}"/*; do
+      local FILENAME
+      FILENAME=$(basename "${FILE}")
+      aws s3 cp "${FILE}" "${DATA_BUCKET}/${FILENAME}"
+      # Allow some time for server to pick up new UDF
+      sleep 60
+      UDF_GHZ_TAGS="{ \"udf_delta_file\": \"${FILENAME}\" }"
+      run_benchmarks
+      aws s3 rm "${DATA_BUCKET}/${FILENAME}"
+    done
+  else
+    run_benchmarks
+  fi
 }
 
 while [[ $# -gt 0 ]]; do
@@ -147,8 +179,20 @@ while [[ $# -gt 0 ]]; do
       CSV_OUTPUT="$2"
       shift 2
       ;;
-    --server-wait-timeout)
-      SERVER_WAIT_TIMEOUT="$2"
+    --snapshot-dir)
+      SNAPSHOT_DIR="$2"
+      shift 2
+      ;;
+    --udf-delta-dir)
+      UDF_DELTA_DIR="$2"
+      shift 2
+      ;;
+    --data-bucket)
+      DATA_BUCKET="$2"
+      shift 2
+      ;;
+    --extra-server-wait-timeout)
+      EXTRA_SERVER_WAIT_TIMEOUT="$2"
       shift 2
       ;;
     --number-of-lookup-keys-list)
@@ -163,31 +207,40 @@ while [[ $# -gt 0 ]]; do
       DESTROY_INSTANCES=1
       shift
       ;;
+    --minimum-server-wait-secs)
+      MINIMUM_SERVER_WAIT_SECS=1
+      shift
+      ;;
     -h | --help) usage 0 ;;
     *) usage ;;
   esac
 done
 
-# No terraform variable overrides, run benchmarks directly
-if [[ -z "${TF_OVERRIDES}" ]]; then
-  deploy_and_benchmark
-  exit 0
+# Check for SNAPSHOT_DIR. If not available, exit.
+if [[ -z "${SNAPSHOT_DIR}" || ! -d "${SNAPSHOT_DIR}" ]]; then
+  printf "snapshot-dir not found:%s\n" "${SNAPSHOT_DIR}"
+  exit 1;
 fi
 
-# Terraform override file found:
-# Each row defines a set of overrides for terraform variables.
-# Pass the overrides to deploy_and_benchmark function and set
-# them as tags in the ghz call.
-while IFS=',' read -ra VARS; do
-  declare -a VAR_OVERRIDES=()
-  EXTRA_GHZ_TAGS="${GHZ_TAGS}"
-  for VAR in "${VARS[@]}"; do
-      VAR_OVERRIDES+=(-var "${VAR}")
-      GHZ_TAG=$(echo "${VAR}" | jq -s -R 'split("\n") | .[0] | split("=") | {(.[0]): .[1]}')
-      EXTRA_GHZ_TAGS=$(jq -s -c 'add' <(echo "${EXTRA_GHZ_TAGS}") <(echo "${GHZ_TAG}"))
-  done
-  deploy_and_benchmark
-done < "${TF_OVERRIDES}"
+# No terraform variable overrides, deploy and benchmark without overrides
+if [[ -z "${TF_OVERRIDES}" ]]; then
+  deploy_and_benchmark "${GHZ_TAGS}"
+else
+  # Terraform override file found:
+  # Each row defines a set of overrides for terraform variables.
+  # Pass the overrides to deploy_and_benchmark function and set
+  # them as tags in the ghz call.
+  while IFS=',' read -ra VARS; do
+    declare -a VAR_OVERRIDES=()
+    DEPLOYMENT_GHZ_TAGS="{}"
+    for VAR in "${VARS[@]}"; do
+        VAR_OVERRIDES+=(-var "${VAR}")
+        OVERRIDE_VAR_GHZ_TAG=$(echo "${VAR}" | jq -s -R 'split("\n") | .[0] | split("=") | {(.[0]): .[1]}')
+        DEPLOYMENT_GHZ_TAGS=$(jq -s -c 'add' <(echo "${DEPLOYMENT_GHZ_TAGS}") <(echo "${OVERRIDE_VAR_GHZ_TAG}"))
+    done
+    deploy_and_benchmark
+  done < "${TF_OVERRIDES}"
+fi
 
 # Benchmarks done, merge CSVs
 
@@ -206,3 +259,5 @@ EXTRA_DOCKER_RUN_ARGS+=" --volume ${CSV_SUMMARY_INPUT_DIR}:${DOCKER_INPUT_DIR} -
   -- \
   --csv-inputs "${DOCKER_BENCHMARK_CSVS[@]}" \
   --csv-output "${DOCKER_OUTPUT_CSV}"
+
+printf "Results in: %s\n" "${CSV_OUTPUT}"
diff --git a/tools/latency_benchmarking/run_benchmarks b/tools/latency_benchmarking/run_benchmarks
--- a/tools/latency_benchmarking/run_benchmarks
+++ b/tools/latency_benchmarking/run_benchmarks
@@ -21,10 +21,9 @@ readonly START
 
 WORKSPACE="$(git rev-parse --show-toplevel)"
 
-BASE_OUTPUT_DIR="${WORKSPACE}/dist/tools/latency_benchmarking/output"
-OUTPUT_DIR="${BASE_OUTPUT_DIR}/${START}"
+BASE_OUTPUT_DIR="${WORKSPACE}/dist/tools/latency_benchmarking/output/${START}"
 
-NUMBER_OF_LOOKUP_KEYS_LIST="1 5 10"
+NUMBER_OF_LOOKUP_KEYS="1 5 10"
 
 DOCKER_OUTPUT_DIR="/tmp/latency_benchmarking/output"
 readonly DOCKER_OUTPUT_DIR
@@ -40,6 +39,52 @@ USAGE
   exit ${exitval}
 }
 
+function generate_requests() {
+  # Create output dirs before calling bazel-debian
+  # If the dir is created in the docker container, we lose write permission
+  for N in "${NUMBER_OF_LOOKUP_KEYS_LIST[@]}"; do
+    mkdir -p "${OUTPUT_DIR}/n=${N}"
+  done
+
+  local -a GENERATE_REQUESTS_ARGS
+  GENERATE_REQUESTS_ARGS+=( --output-dir "${DOCKER_OUTPUT_DIR}" )
+  GENERATE_REQUESTS_ARGS+=( --number-of-keys-list "${NUMBER_OF_LOOKUP_KEYS_LIST[@]}" )
+  # Mount the output dir to docker and write requests to output dir for each item in
+  # `NUMBER_OF_LOOKUP_KEYS_LIST`.
+  # This will write a json request for each NUMBER_OF_LOOKUP_KEY=N to
+  # dist/tools/latency_benchmarking/output/${START}/${SNAPSHOT_FILENAME}/n=${N}/request.json
+  EXTRA_DOCKER_RUN_ARGS+=" --volume ${OUTPUT_DIR}:${DOCKER_OUTPUT_DIR} " \
+    builders/tools/bazel-debian run //tools/latency_benchmarking:generate_requests \
+    -- "${GENERATE_REQUESTS_ARGS[@]}"
+}
+
+function run_ghz_for_requests() {
+  # Iterate through the generated request.json files and call `ghz` to benchmark server at ${SERVER_ADDRESS}
+  for N in "${NUMBER_OF_LOOKUP_KEYS_LIST[@]}" ; do
+    DIR=${OUTPUT_DIR}/n=${N}
+    REQUEST_JSON="${DIR}"/request.json
+    if [[ ! -f "${REQUEST_JSON}" ]]; then
+      continue
+    fi
+
+    printf "Running ghz for number of keys %s\n" "${N}"
+    BASE_GHZ_TAGS='{"number_of_lookup_keys": "'"${N}"'", "keys_from_file": "'"${SNAPSHOT_FILENAME}"'"}'
+    TAGS=$(jq -s -c 'add' <(echo "${GHZ_TAGS}") <(echo "${BASE_GHZ_TAGS}"))
+    GHZ_OUTPUT_JSON_FILE="${DIR}/ghz_output.json"
+    ghz --protoset "${WORKSPACE}/dist/query_api_descriptor_set.pb" \
+      -D "${REQUEST_JSON}" \
+      --duration=5s \
+      --skipFirst=100 \
+      --concurrency=100 \
+      --format=pretty \
+      --tags "${TAGS}" \
+      --output "${GHZ_OUTPUT_JSON_FILE}" \
+      --call kv_server.v2.KeyValueService/GetValuesHttp \
+      "${SERVER_ADDRESS}"
+  done
+}
+
+
 while [[ $# -gt 0 ]]; do
   case "$1" in
     --server-address)
@@ -47,11 +92,15 @@ while [[ $# -gt 0 ]]; do
       shift 2 || usage
       ;;
     --number-of-lookup-keys-list)
-      NUMBER_OF_LOOKUP_KEYS_LIST="$2"
+      NUMBER_OF_LOOKUP_KEYS="$2"
       shift 2
       ;;
     --ghz-tags)
       GHZ_TAGS="$2"
+      shift 2
+      ;;
+    --snapshot-dir)
+      SNAPSHOT_DIR="$2"
       shift 2
       ;;
     -h | --help) usage 0 ;;
@@ -59,53 +108,34 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-# Create output dirs before calling bazel-debian
-# If the dir is created in the docker container, we lose write permission
-mkdir -p "${OUTPUT_DIR}"
-IFS=' ' read -ra NUMBER_OF_LOOKUP_KEYS <<< "${NUMBER_OF_LOOKUP_KEYS_LIST}"
-for N in "${NUMBER_OF_LOOKUP_KEYS[@]}"; do
-  mkdir -p "${OUTPUT_DIR}/n=${N}"
+# Check for SNAPSHOT_DIR. If not available, exit.
+if [[ -z "${SNAPSHOT_DIR}" || ! -d "${SNAPSHOT_DIR}" ]]; then
+  printf "snapshot-dir not found:%s\n" "${SNAPSHOT_DIR}"
+  exit 1;
+fi
+
+# Iterate through each snapshot file and
+#   1. create requests under dist/tools/latency_benchmarking/output/${START}/${SNAPSHOT_FILENAME}
+#   2. for each request, run benchmarks with ghz
+IFS=' ' read -ra NUMBER_OF_LOOKUP_KEYS_LIST <<< "${NUMBER_OF_LOOKUP_KEYS}"
+for SNAPSHOT_FILE in "${SNAPSHOT_DIR}"/*; do
+  SNAPSHOT_FILENAME=$(basename "${SNAPSHOT_FILE}")
+  OUTPUT_DIR="${BASE_OUTPUT_DIR}/${SNAPSHOT_FILENAME}"
+  # Copy snapshot file over to SNAPSHOT_0000000000000001 so that bazel can create a CSV
+  # to pass to generate_requests.py
+  cp "${SNAPSHOT_FILE}" "${WORKSPACE}/tools/latency_benchmarking/SNAPSHOT_0000000000000001"
+  generate_requests
+  run_ghz_for_requests
+  # Remove SNAPSHOT_0000000000000001
+  rm "${WORKSPACE}/tools/latency_benchmarking/SNAPSHOT_0000000000000001"
 done
 
-# Mount the output dir to docker and write requests to output dir for each item in
-# `NUMBER_OF_LOOKUP_KEYS_LIST`.
-# This will write a json request for each NUMBER_OF_LOOKUP_KEY=N to
-# dist/tools/latency_benchmarking/output/${START}/n=${N}/request.json
-# shellcheck disable=SC2086
-EXTRA_DOCKER_RUN_ARGS+=" --volume ${OUTPUT_DIR}:${DOCKER_OUTPUT_DIR} " \
-  builders/tools/bazel-debian run //tools/latency_benchmarking:generate_requests \
-  -- \
-  --output-dir ${DOCKER_OUTPUT_DIR} \
-  --number-of-keys-list ${NUMBER_OF_LOOKUP_KEYS_LIST}
-
-# Iterate through the generated request.json files and call `ghz` to benchmark server at ${SERVER_ADDRESS}
-for N in "${NUMBER_OF_LOOKUP_KEYS[@]}" ; do
-  DIR=${OUTPUT_DIR}/n=${N}
-  REQUEST_JSON="${DIR}"/request.json
-  if [[ ! -f "${REQUEST_JSON}" ]]; then
-    continue
-  fi
-
-  printf "Running ghz for number of keys %s\n" "${N}"
-  BASE_GHZ_TAGS='{"number_of_lookup_keys": "'"${N}"'"}'
-  TAGS=$(jq -s -c 'add' <(echo "${GHZ_TAGS}") <(echo "${BASE_GHZ_TAGS}"))
-  GHZ_OUTPUT_JSON_FILE="${DIR}/ghz_output.json"
-  ghz --protoset "${WORKSPACE}/dist/query_api_descriptor_set.pb" \
-    -D "${REQUEST_JSON}" \
-    --duration=5s \
-    --skipFirst=100 \
-    --concurrency=100 \
-    --format=pretty \
-    --tags "${TAGS}" \
-    --output "${GHZ_OUTPUT_JSON_FILE}" \
-    --call kv_server.v2.KeyValueService/GetValuesHttp \
-    "${SERVER_ADDRESS}"
-done
-
-EXTRA_DOCKER_RUN_ARGS+=" --volume ${OUTPUT_DIR}:${DOCKER_OUTPUT_DIR} " \
+# Go through all the ghz results in dist/tools/latency_benchmarking/output/${START}
+# and collect the summary in a csv
+EXTRA_DOCKER_RUN_ARGS+=" --volume ${BASE_OUTPUT_DIR}:${DOCKER_OUTPUT_DIR} " \
   builders/tools/bazel-debian run //tools/latency_benchmarking:create_csv_summary \
   -- \
   --ghz-result-dir ${DOCKER_OUTPUT_DIR}
 
 echo "Result in:"
-echo "${OUTPUT_DIR}/summary.csv"
+echo "${BASE_OUTPUT_DIR}/summary.csv"
