Release 0.10.0 (2023-05-04) (#38) (#39)
### Features

* Add --fast option for running functional tests
* Add a multi-KV SUT
* Add baseline for SSP
* Add bazel macro to generate OpenSSL certificates
* Add brotli compression support
* Add envoy for KV server in baseline SUT
* Add envoy frontend in baseline SUT
* Add optional filename arg to tools/collect-logs
* Add SUT without UDF
* Add terraform support for sharding
* Drop data meant for other shards
* Include tink_cc repository
* Set timestamp for generated delta files for SUTs
* Support selection of single SUT for testing
* Upgrade gRPC to v1.52.1
* Upgrade to functionaltest-system 0.5.1
* Use 443 for http1.1 and 8443 for http2.
* Use scp deps exposed by data-plane-shared-libraries repo
* Use shared control plane skylark functions for transitive dependencies

### Bug Fixes

* Address linter issues in production dir
* Address linter issues in tools
* Avoid running prettier on PCR0 files
* Capture test logs into zip archive
* Collect logs from functional testing
* Configure docker compose to pull images quietly
* Correct container deps in multiple-kv-servers
* Defer to data-plane-shared cpp deps
* Remove exposed ports as not needed within docker network
* Remove unused code in tools/get_workspace_status
* Remove workspace parent dirs from logs archive
* Upgrade pre-commit hooks

### Documentation

* Add Protected Audience API rename banner

Bug: 280464254
Change-Id: I3577b3dd6124c8cad66717b1c43b774e3d445fe5
GitOrigin-RevId: e8331cb873bd61ed708ee1e62fcf108c684e53af

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/testing/functionaltest-system/bazel/grpcurl_diff_test_runner b/testing/functionaltest-system/bazel/grpcurl_diff_test_runner
--- a/testing/functionaltest-system/bazel/grpcurl_diff_test_runner
+++ b/testing/functionaltest-system/bazel/grpcurl_diff_test_runner
@@ -7,7 +7,10 @@ function usage() {
   cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
-    --endpoint-env-var <ENDPOINT>   name of env var containing endpoint host:port
+    --endpoint-hostport <host:port> host:port string
+    --endpoint-type <type>          protocol: grpc or http
+    --docker-network <name>         docker network
+    --protoset <filename>           protobuf spec image file
     --rpc <rpc name>                rpc name
     --request <filename>            request.json filename
     --jq-pre-filter <filename>      jq program to transform the request
@@ -15,8 +18,6 @@ usage:
     --jq-post-slurp                 run jq postprocessor in stream slurp mode
     --reply <filename>              golden reply against which to diff the output
 environment variables:
-    <ENDPOINT>                      host:port of grpc endpoint
-    DOCKER_NETWORK                  docker network name
     TEST_TOOLS_IMAGE                docker image uri for test tools
 USAGE
   # shellcheck disable=SC2086
@@ -27,8 +28,16 @@ declare -i JQ_POST_SLURP=0
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    --endpoint-env-var)
-      ENDPOINT_VAR="$2"
+    --endpoint-hostport)
+      ENDPOINT_HOSTPORT="$2"
+      shift 2
+      ;;
+    --endpoint-type)
+      ENDPOINT_TYPE="$2"
+      shift 2
+      ;;
+    --docker-network)
+      DOCKER_NETWORK="$2"
       shift 2
       ;;
     --rpc)
@@ -59,23 +68,27 @@ while [[ $# -gt 0 ]]; do
       JQ_POST_SLURP=1
       shift
       ;;
-    --help | -h)
-      usage 0
-      ;;
-    *)
-      usage 1
-      break
-      ;;
+    --help | -h) usage 0 ;;
+    *) usage 1 ;;
   esac
 done
 
+set -o xtrace
+
+if [[ ${ENDPOINT_TYPE} == grpc ]]; then
+  RUNNER_APP=grpcurl
+  : "${PROTOSET_FILENAME?"Error: --protoset must be specified"}"
+elif [[ ${ENDPOINT_TYPE} == http ]]; then
+  RUNNER_APP=curl
+else
+  printf "Error: --endpoint-type must be a valid type: grpc or http\n"
+  exit 1
+fi
+
 : "${RPC?"Error: --rpc must be specified"}"
-: "${PROTOSET_FILENAME?"Error: --protoset must be specified"}"
 : "${REQUEST_FILENAME?"Error: --request must be specified"}"
 : "${GOLDEN_REPLY?"Error: --reply must be specified"}"
-: "${ENDPOINT_VAR?"Error: --endpoint-env-var not specified"}"
-declare -r ENDPOINT="${!ENDPOINT_VAR}"
-: "${ENDPOINT?"Error: Endpoint host:port not specified in ${ENDPOINT_VAR} env var"}"
+: "${ENDPOINT_HOSTPORT?"Error: --endpoint-hostport not specified"}"
 : "${TEST_TOOLS_IMAGE?"Error: Test tools image URI not specified in TEST_TOOLS_IMAGE env var"}"
 
 REQ_JSON="$(cat "${REQUEST_FILENAME}")"
@@ -87,41 +100,61 @@ function cleanup() {
   exit ${STATUS}
 }
 
-declare -a DOCKER_ARGS
+declare -a DOCKER_ARGS=(
+  "--rm"
+  "--interactive"
+  "--entrypoint=/bin/bash"
+  "--tmpfs=/work"
+  "--workdir=/work"
+)
 if [[ -n ${DOCKER_NETWORK} ]]; then
-  DOCKER_ARGS+=(
-    --network
-    "${DOCKER_NETWORK}"
-  )
+  DOCKER_ARGS+=("--network=${DOCKER_NETWORK}")
 fi
 if [[ -s ${JQ_PRE_PROGRAM_FILENAME} ]]; then
   JQ_PRE_PROGRAM="$(cat "${JQ_PRE_PROGRAM_FILENAME}")"
 fi
+declare -a JQ_POST_ARGS=(
+  --from-file post-filter.jq
+)
 if [[ -s ${JQ_POST_PROGRAM_FILENAME} ]]; then
   JQ_POST_PROGRAM="$(cat "${JQ_POST_PROGRAM_FILENAME}")"
   if [[ ${JQ_POST_SLURP} -eq 1 ]]; then
-    JQ_POST_ARGS="--slurp"
+    JQ_POST_ARGS+=(--slurp)
   fi
 fi
-docker run -i "${DOCKER_ARGS[@]}" --entrypoint /bin/bash --tmpfs /work --workdir /work "${TEST_TOOLS_IMAGE}" -c "
+docker run "${DOCKER_ARGS[@]}" "${TEST_TOOLS_IMAGE}" -c "
 set -o errexit
-cat /dev/stdin >protoset.pb
 if [[ -n '${JQ_PRE_PROGRAM}' ]]; then
-  echo '${JQ_PRE_PROGRAM}' >pre-filter.jq
-  jq --exit-status --from-file pre-filter.jq >grpcurl.in <<EOF
+  cat >pre-filter.jq <<EOF
+${JQ_PRE_PROGRAM}
+EOF
+  jq --exit-status --from-file pre-filter.jq >rpc_request <<EOF
 ${REQ_JSON}
 EOF
 else
-  cat >grpcurl.in <<EOF
+  cat >rpc_request <<EOF
 ${REQ_JSON}
 EOF
 fi
-grpcurl -plaintext -d @ -protoset protoset.pb ${ENDPOINT} ${RPC} <grpcurl.in >grpcurl.out
+case ${RUNNER_APP} in
+  grpcurl)
+    cat /dev/stdin >protoset.pb
+    grpcurl -plaintext -d @ -protoset protoset.pb ${ENDPOINT_HOSTPORT} ${RPC} <rpc_request >rpc_reply
+    ;;
+  curl)
+    curl --silent --data @rpc_request --output rpc_reply http://${ENDPOINT_HOSTPORT}/${RPC%.*}/${RPC##*.}
+    ;;
+  *) exit 4 ;;
+esac
 if [[ -n '${JQ_POST_PROGRAM}' ]]; then
-  echo '${JQ_POST_PROGRAM}' >post-filter.jq
-  jq ${JQ_POST_ARGS} --from-file post-filter.jq <grpcurl.out
+  cat >post-filter.jq <<EOF
+${JQ_POST_PROGRAM}
+EOF
+  jq ${JQ_POST_ARGS[*]} <rpc_reply
 else
-  cat grpcurl.out
+  jq . <rpc_reply
 fi
-" <"${PROTOSET_FILENAME}" >"${TMP_REPLY}"
+" \
+  <"${PROTOSET_FILENAME}" \
+  >"${TMP_REPLY}"
 diff "${TMP_REPLY}" "${GOLDEN_REPLY}"
diff --git a/testing/functionaltest-system/tests/run-tests b/testing/functionaltest-system/tests/run-tests
--- a/testing/functionaltest-system/tests/run-tests
+++ b/testing/functionaltest-system/tests/run-tests
@@ -25,6 +25,12 @@ function _cleanup() {
   if [[ ${STATUS} -ne 0 ]]; then
     printf "Error: run-tests status code: %d\n" "${STATUS}" &>/dev/stderr
   fi
+  if [[ ${#DOCKER_COMPOSE_ARGS} -gt 0 ]]; then
+    docker compose "${DOCKER_COMPOSE_ARGS[@]}" down || true
+  fi
+  if [[ -d ${DATA_DIR} ]]; then
+    rm -rf "${DATA_DIR}"
+  fi
   exit ${STATUS}
 }
 
@@ -32,17 +38,24 @@ function usage() {
   declare -r -i exitval=$?
   cat &>/dev/stderr <<USAGE
 usage:
-  $0 <options>
-      --network <name>    docker network name
+  $0 [options]
+    --verbose        Produce verbose output
+    --no-load-image  Skip building and loading image
 USAGE
   exit ${exitval}
 }
 
+declare -i SKIP_LOAD_IMAGE=0
+
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    --network)
-      DOCKER_NETWORK="$2"
-      shift 2
+    --no-load-image)
+      SKIP_LOAD_IMAGE=1
+      shift
+      ;;
+    --verbose)
+      set -o xtrace
+      shift
       ;;
     -h | --help) usage 0 ;;
     *)
@@ -52,18 +65,74 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-: "${DOCKER_NETWORK?"--network flag not specified"}"
+function load_image() {
+  if [[ ${SKIP_LOAD_IMAGE} -eq 1 ]]; then
+    return
+  fi
+  # build docker image then load it into local docker client
+  local -r _tmpout=$(mktemp)
+  trap 'rm -f "${_tmpout}"' RETURN
+  declare -r _target=//"${SRV_IMAGE#bazel/}"
+  "${TOOLS_DIR}"/bazel-debian build "${_target}"
+  if ! "${TOOLS_DIR}"/bazel-debian run "${_target}" &>"${_tmpout}"; then
+    printf "bazel build %s failed\n" "${_target}"
+    cat "${_tmpout}"
+    rm -f "${_tmpout}"
+    exit 1
+  fi
+}
+
+function get_sut_data_configs() {
+  declare -r target_dir="$1"
+  "${TOOLS_DIR}"/bazel-debian run //tests:copy_to_dist
+  cp "${WORKSPACE}"/dist/sut_data.zip "${target_dir}"
+  EXTRA_DOCKER_RUN_ARGS="--volume ${target_dir}:/data --workdir /data" \
+    "${TOOLS_DIR}"/unzip sut_data.zip
+  rm -f "${target_dir}"/sut_data.zip
+  cp "${TESTS_DIR}"/docker-compose.{env,yaml} "${target_dir}"
+  cat <<EOF >"${target_dir}"/docker-compose-data.env
+DATA_DIR="${target_dir}"
+EOF
+  chmod 444 "${target_dir}"/*
+}
+
+function ensure_docker_compose() {
+  if ! docker compose version --short | grep -q ^2\. &>/dev/null; then
+    printf "docker compose v2 is required\n" &>/dev/stderr
+    exit 1
+  fi
+}
+
+ensure_docker_compose
 
 TESTS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 readonly TESTS_DIR
-readonly TOOLS_DIR="${TESTS_DIR}"/../builders/tools
+readonly WORKSPACE="${TESTS_DIR}"/..
+readonly TOOLS_DIR="${WORKSPACE}"/builders/tools
 
-declare -a TEST_ARGS=(
-  "--test_env=GREETER_ENDPOINT=greeter:50051"
-  "--test_env=ROUTEGUIDE_ENDPOINT=route_guide:50051"
-  "--test_env=DOCKER_NETWORK=${DOCKER_NETWORK}"
+declare -a -r TEST_ARGS=(
   "--test_env=TEST_TOOLS_IMAGE=$("${TOOLS_DIR}"/get-builder-image-tagged --image test-tools)"
 )
+declare -a TESTS=(
+  //tests:all_tests
+)
+declare -r SRV_IMAGE=bazel/tests/servers:grpc_examples_docker_image
 
-declare -a TESTS=("//tests/test_cases/grpc:all")
+load_image
+
+DATA_DIR="$(mktemp --directory)"
+readonly DATA_DIR
+get_sut_data_configs "${DATA_DIR}"
+
+declare -a -r DOCKER_COMPOSE_ARGS=(
+  --file "${DATA_DIR}"/docker-compose.yaml
+  --env-file "${DATA_DIR}"/docker-compose.env
+  --env-file "${DATA_DIR}"/docker-compose-data.env
+)
+
+docker compose "${DOCKER_COMPOSE_ARGS[@]}" up --quiet-pull --detach
+
+if command bazel --help &>/dev/null; then
+  bazel test "${TESTS[@]}" "${TEST_ARGS[@]}"
+fi
 "${TOOLS_DIR}"/bazel-debian test "${TESTS[@]}" "${TEST_ARGS[@]}"
