Release 0.8.0
### Features

* add AWS SQS ReceiveMessage latency histogram
* Add command line flags for parameters
* Add configurable thread count for realtime updater
* Add functional test
* Adding e2e latency measurement for realtime updates
* Allow specifying explicit histogram bucket boundaries
* Allow the blob_storage_util cp command to work with local files.
* Allow the DeltaFileRecordChangeNotifier to read local files as well as from S3
* Batch delete SQS messages
* Build delta files from csv
* clean up realtime queues
* Configure AWS hosted Prometheus.
* Disable the use of exceptions
* Enhance/Simplify local export of telemetry with OTLP.
* Functional testing of local server with delta files
* make AwsSnsSqsManager thread safe
* Make the blob_storage_change_watcher tool work for local files
* Make the blob_storage_util cat and rm commands work for local files
* Make the blob_storage_util ls command work for local files and refactor out common parts from the AWS binary
* Make the delta_file_watcher tool work for local files
* Move the platform specific server configuration logic to a separate file
* multi-threaded realtime notifier
* realtime tester in a container
* Reuse SQS client
* Speed up test updates publisher
* Tools for generating and inserting realtime test data.
* Upgrade build-system to release-0.18.0
* Upgrade build-system to release-0.20.0
* Upgrade debian runtime images to 15 Feb 2023
* Upgrade to build-system 0.17.0
* Use a PlatformInitializer so the data_cli will compile for --platform=local

### Bug Fixes

* Add ability to interrupt a SleepFor Duration.
* Add minimum shard size threshold for concurrent reader.
* Launch Envoy first before all other processes.
* Make MetricsRecorder a shared global instance.
* Only run functional tests against local server
* Remove functionaltest/run-server, update docs accordingly
* Remove submodule section from docs
* Run server in background, and reduce noise
* Run server using delta files in run-server-docker
* Update generate_load_test_data to use bazel-debian
* Use symlink for identical test replies
* Use VLOG for concurrent reader debugging logs.
* Wait for envoy to respond before launching enclave service.

### Documentation

* Add a playbook template for new alerts
* Add description for backup_poll_frequency_secs
* Add docs about how to run the server locally
* fix /tmp/deltas discrepancy
* remove obsolete service
* Updating instructions on how to copy `eif` manually.

### Terraform

* Convert tfvar files to json
* Support Prometheus service running in a different region

Change-Id: I67f31c6d05015b4674e1a9600ce7f190af46e390
Bug: 275543946
GitOrigin-RevId: 41c735e45b2e5f6553caef9584a670d8a83a095b

diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -31,6 +31,11 @@ function _print_runtime() {
   else
     printf "Error: build_and_test_in_docker completed with status code: %s\n" "${STATUS}" &>/dev/stderr
   fi
+  # kokoro has a habit of truncating build logs for scripts, adding a delay
+  # seems to help ensure completeness
+  if [[ -v KOKORO_ARTIFACTS_DIR ]]; then
+    sleep 5s
+  fi
   exit ${STATUS}
 }
 
@@ -67,6 +72,7 @@ SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 readonly SCRIPT_DIR
 # shellcheck source=builders/tools/builder.sh
 source "${SCRIPT_DIR}"/../../builders/tools/builder.sh
+source "${SCRIPT_DIR}"/lib_local_server.sh
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -125,20 +131,38 @@ builder::cbuild_debian "
 trap _collect_logs EXIT
 function _collect_logs() {
   local -r -i STATUS=\$?
-  printf 'Collecting bazel logs...\n' &>/dev/stderr
-  bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //:collect-logs
+  printf 'Collecting bazel logs... [status: %d]\n' \${STATUS} &>/dev/stderr
+  if ! bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //:collect-logs; then
+    printf 'Error collecting logs\n'
+  fi
   exit \${STATUS}
 }
 set -o errexit
 bazel ${BAZEL_STARTUP_ARGS} build ${BAZEL_EXTRA_ARGS} //components/... //public/... //tools/...
 bazel ${BAZEL_STARTUP_ARGS} test ${BAZEL_EXTRA_ARGS} --build_tests_only --test_size_filters=small //...
 bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //production/packaging/aws/data_server:copy_to_dist
+bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //testing/functionaltest:copy_to_dist
 "
 
-DIST="${WORKSPACE}"/dist
-if [[ -d ${DIST} ]]; then
+function find_unused_port() {
+  declare -i port
+  for port in {50050..50150}; do
+    if ! echo "" >/dev/tcp/127.0.0.1/${port}; then
+      printf "%d" ${port}
+      return
+    fi
+  done 2>/dev/null
+  exit 1
+}
+
+readonly DIST="${WORKSPACE}"/dist
+if ! [[ -d ${DIST} ]]; then
+  printf "dir not found: [%s]\n" "${DIST}"
+else
+  if [[ ${PLATFORM} == local ]]; then
+    set -o xtrace
+    local_server::run_and_test
+  fi
   printf "build artifacts:\n"
   ls -lhR "${DIST}"
-else
-  printf "dir not found: [%s]\n" "${DIST}"
 fi
