Release 0.2.0
* Add arg processing to cbuild script (b45ca62)
* Add bazel-debian helper script (c0b38b4)
* Add black python formatter to pre-commit (6d079d9)
* Add optional flags to cbuild tool (6b68d11)
* Inject clang-version as a bazel action_env (40af734)
* Migrate generation of builders/release container image to Dockerfile (abb70a8)
* Remove python build dependencies from bazel (81dcb7a)
* Support installation of git pre-commit hook (b7c565a)
* Support running the server container locally (8370503)
* Use EC2 instance connect for ssh access. (604e3b5)

* Add public/ to presubmit tests (2d0056a)
* Add python version to action_env (8e0e074)
* Add require-ascii pre-commit hook (50eb751)
* Add/remove basic pre-commit hooks (f8e46cd)
* Allow for short(er) presubmit builds (8656da5)
* Change ownership of dist/ to user (d7282a2)
* Correct git instructions at the end of cut_release (76c19de)
* Define python3 toolchain (fa83525)
* Ensure /etc/gitconfig is readable by all (f0c82c2)
* Install bazel version as specified in .bazelversion (00d6f63)
* Move bazel env vars from comments to help text (32b2f6f)
* Pin version of bazelisk (face7df)
* Pin version of libc++-dev (08b8d7a)
* Pin version of python3.8 (ad9c61f)
* Remove check for uncommitted changes, tools/pre-commit exit status should suffice (b96636c)
* Tidy cut_release (51f1b0a)
* Upgrade zstd to v1.5.2 (ba7bda1)

* Add buildifier tool to pre-commit (1904652)
* Add terraform fmt to pre-commit (0ba7623)
* Add terraform to tools (96ef5ee)
* Add tools/pre-commit (6083417)
* Adjust branch specification for mirroring to GitHub (a004730)
* Move commit-and-tag-version into tools dir (73e0c42)
* Move gh into tools dir (d6a15c1)
* Reduce redundant installation commands (59b93c8)
* Reinstate use of cpplint, via pre-commit tool (be0b5e5)
* Remove buildifier from bazel build as it is redundant with pre-commit (db6b139)
* Remove release-please tool (6bcd54a)
* Rename builders/bazel to build-debian (71b81b0)

Change-Id: I05dc2ef05ec7f1cad66bb5d81cc856692fa59381
GitOrigin-RevId: 3efdf86dbdc8f7aae24344bf65f0cadd42ada019

diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -16,25 +16,67 @@
 
 set -o pipefail
 set -o errexit
+set -o xtrace
+export PS4='+\t ' # xtrace prompt
+
+START=$(date +%s)
+
+trap _print_runtime EXIT
+
+function _print_runtime() {
+  local END=$(date +%s)
+  env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) > /dev/stderr
+}
 
 CLEAN=0
 BUILD_AND_TEST_ALL_ARGS=
+PRESUBMIT=0
+PRECOMMIT_ONLY=0
+WITH_SHARED_CACHE=1
+WITH_DOCKER_SOCK=1
+readonly IMAGE_TAGGED=privacysandbox/builders/build-debian:bazel_build_image
 
 usage() {
   local exitval=${1-1}
   cat >&2 << USAGE
 usage:
   $0 <options>
-    --with-ami                Build the AMI. Default: false
-    --clean                   Optionally clean build cache before running build
-    --debug                   Emit debug build info. Default: false
+    --without-shared-cache       Use a container-local cache
+    --without-embedded-docker    Enable docker client within container
+    --precommit-only             Run precommit then exit
+    --with-ami                   Build the AMI
+    --remove-output-base         Remove the bazel output-base dir after building
+    --clean                      Optionally clean build cache before running build
+
+environment variables (all optional):
+    WORKSPACE                    Set the path to the workspace (repo root)
+    BAZEL_STARTUP_ARGS           Additional startup arguments to pass to bazel invocations
+    BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
+    EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
 USAGE
   exit ${exitval}
 }
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    --with-ami | --debug)
+    --precommit-only)
+      PRECOMMIT_ONLY=1
+      shift
+      ;;
+    --without-shared-cache)
+      WITH_SHARED_CACHE=0
+      shift
+      ;;
+    --without-embedded-docker)
+      WITH_DOCKER_SOCK=0
+      shift
+      ;;
+    --presubmit)
+      BUILD_AND_TEST_ALL_ARGS="${BUILD_AND_TEST_ALL_ARGS} $1"
+      PRESUBMIT=1
+      shift
+      ;;
+    --with-ami | --remove-output-base)
       BUILD_AND_TEST_ALL_ARGS="${BUILD_AND_TEST_ALL_ARGS} $1"
       shift
       ;;
@@ -53,19 +95,74 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-WORKSPACE=$(bazel info workspace)
+function cbuild() {
+  declare -a EXTRA_DOCKER_ARGS
 
-CBUILD="${WORKSPACE}/builders/bazel/cbuild"
+  # build container image and load it into the local docker client
+  if ! docker image inspect ${IMAGE_TAGGED} >/dev/null 2>&1; then
+    tar --create --dereference --gzip --directory=${WORKSPACE}/builders/build-debian . |
+    docker build - --tag ${IMAGE_TAGGED}
+  fi
+  if [[ ${WITH_DOCKER_SOCK} -eq 1 ]]; then
+    EXTRA_DOCKER_ARGS+=(
+      -v /var/run/docker.sock:/var/run/docker.sock
+    )
+  fi
+  if [[ ${WITH_SHARED_CACHE} -eq 1 ]]; then
+    EXTRA_DOCKER_ARGS+=(
+      -v "${HOME}/.cache/bazel:/root/.cache/bazel"
+    )
+  fi
+  if [[ -n ${AWS_ACCESS_KEY_ID} ]]; then
+    EXTRA_DOCKER_ARGS+=(
+      --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+      --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+    )
+  fi
+  if [[ -n ${BAZEL_EXTRA_ARGS} ]]; then
+    EXTRA_DOCKER_ARGS+=(
+      --env BAZEL_EXTRA_ARGS
+    )
+  fi
+  if [[ -n ${BAZEL_STARTUP_ARGS} ]]; then
+    EXTRA_DOCKER_ARGS+=(
+      --env BAZEL_STARTUP_ARGS
+    )
+  fi
 
-if [[ $CLEAN -eq 1 ]]; then
-  ${CBUILD} -c "bazel clean"
+  if ! [[ -t 1 ]]; then
+    TTY_OUTPUT='| tail -f'
+  fi
+  docker run --rm \
+    --entrypoint=/bin/bash \
+    -v "${WORKSPACE}:/src/workspace" \
+    -w /src/workspace \
+    "${EXTRA_DOCKER_ARGS[@]}" \
+    ${EXTRA_DOCKER_RUN_ARGS} \
+    ${IMAGE_TAGGED} \
+    -c "$@ ${TTY_OUTPUT}"
+}
+
+WORKSPACE=${WORKSPACE-$(bazel info workspace)}
+
+if [[ ${CLEAN} -eq 1 ]]; then
+  cbuild "bazel clean --expunge_async ${BAZEL_ARGS}"
+  exit
 fi
 
-# TODO(b/242876887): Let user own the artifacts
-mkdir -p ${WORKSPACE}/dist
-${CBUILD} production/packaging/build_and_test_all ${BUILD_AND_TEST_ALL_ARGS}
+${WORKSPACE}/tools/pre-commit
+if [[ ${PRECOMMIT_ONLY} -eq 1 ]]; then
+  exit 0
+fi
 
-cat << OUTPUT
-location of the output:
-$(ls -lh ${WORKSPACE}/dist)
-OUTPUT
+cbuild "production/packaging/build_and_test_all ${BUILD_AND_TEST_ALL_ARGS}"
+
+if [[ ${PRESUBMIT} -eq 0 ]]; then
+  if [[ -d ${WORKSPACE}/dist ]]; then
+    cbuild "chgrp --recursive $(id -g) dist/ && chown --recursive $(id -u) dist/"
+    printf "location of the build artifacts:\n"
+    ls -lh ${WORKSPACE}/dist
+  else
+    printf "${WORKSPACE}/dist dir not found\n"
+  fi
+fi
