Release 0.4.0 (#17)
### Features

* Add //:buildifier rule as an alias to the pre-commit buildifier hook
* Add a debugging endpoint for Binary Http GetValues.
* Add aws-cli helper script
* Add csv reader and writer
* Add delta record reader based on riegeli stream io.
* Add library for reading and writing delta files
* Add utility for data generation (currently supports csv to delta and vice versa)
* Add version info to server binaries
* Determine workspace mount point from docker inspect if inside docker container
* Display pre-commit error log if it exists
* Implement API call to record lifecycle heartbeat.
* Log bazel build flags during server startup runtime.
* Overhaul building on amazonlinux2
* Repeating timer with callback implementation
* Set working dir to current workspace-relative path in tools/terraform

### Bug Fixes

* Add bazel rule to copy files to dist dir
* Add builders/tools/normalize-dist to chmod/chgrp/chown dist/ directory tree
* Add fetch git tags from remote prior to syncing repos
* Add files to subject to chown and chgrp
* Adjust chown/chgrp to be silent
* Adopt shellcheck
* Clean bazel_root for smaller docker image
* Correct the WORKSPACE path in production/packaging/aws/build_and_test
* Correct variable used to check for valid repo name
* Drop packer from build-debian image
* Fix a typo and improve some logging for DataOrchestrator's loading
* Improve cbuild help text
* Improve git push message to accommodate patch branches
* Increase SQS cleanup lamabda timeout
* Modifications as indicated by shellcheck
* Modify build and packaging for AWS SQS Lambda
* Move definition from header to cc to eliminate linker error
* Only propagate AWS env vars into amazonlinux2 build container
* pre-commit CLEANUP should default to zero
* Print pre-commit version rather than help
* Print timestamps in UTC timezone
* Remove container when get-architecture exits
* Remove duplicate text "instance:" in build flavor
* Remove shellcheck from build-debian
* Remove unused nitro_enclave_image bazel rule
* Set bazel output_user_root in image bazelrc
* Set locale in build-debian
* Strip commit hashes from CHANGELOG.md
* Switch from hardcoded arch to using dpkg --print-architecture
* Update author name
* Update pre-commit to use cbuild
* Use --with-ami flag to determine bazel flags instance/platform
* Use default health check grace priod (300s) now that we have heartbeats.
* Use git rather than bazel to determine workspace root
* Use PRE_COMMIT_TOOL env var

### Build System

* Add arch to docker image tags
* Add get_builder_image_tagged tool to determine a content-based tag
* Add get-architecture helper script
* Propagate status code in exit functions

### Documentation

* Correct command to load docker image locally
* Instructions to make changes to a dependency
* Sugggest use of python virtualenv
* Use concise form of passing env vars into docker container

Change-Id: Id86dbad94962a2b3c3f53c870f18c0b546c1725b
GitOrigin-RevId: f46fc5f2a70f81309a5733c5185d192f645863a7

Co-authored-by: Privacy Sandbox Team <noreply@google.com>

diff --git a/builders/tools/cbuild b/builders/tools/cbuild
--- a/builders/tools/cbuild
+++ b/builders/tools/cbuild
@@ -16,17 +16,17 @@ set -o pipefail
 set -o errexit
 
 IMAGE="build-debian"
-declare -r -A IMAGE_LIST=(
-  [build-debian]="privacysandbox/builders/build-debian:bazel_build_image"
-  [build-amazonlinux2]="privacysandbox/builders/build-amazonlinux2:bazel_build_image"
+VERBOSE=0
+declare -r -a IMAGE_LIST=(
+  "build-debian"
+  "build-amazonlinux2"
+  "presubmit"
 )
 
 declare -a ENV_VARS
 ENV_VARS+=(
-  "AWS_ACCESS_KEY_ID"
-  "AWS_SECRET_ACCESS_KEY"
-  "BAZEL_EXTRA_ARGS"
   "BAZEL_STARTUP_ARGS"
+  "BAZEL_EXTRA_ARGS"
 )
 
 usage() {
@@ -38,25 +38,24 @@ usage:
     --image                    Image name for the build runtime. Valid names:
 USAGE
 
-  for elem in "${!IMAGE_LIST[@]}"
+  for elem in "${IMAGE_LIST[@]}"
   do
-    if [[ ${IMAGE} == "${elem}" ]]; then
-      local EXTRA=" (default)"
-    fi
-    printf "                                   *  %s%s\n" "${elem}" "${EXTRA}" &>/dev/stderr
+    printf "                                   *  %s\n" "${elem}" &>/dev/stderr
   done
 
   cat &>/dev/stderr << USAGE
-    --env <key>[=<value>]      Name of exported environment variable, or name=value
+    --env <key>[=<value>]      Name (or name=value) of exported environment variable, propagated into container
     --without-shared-cache     Containers will not mount ${HOME}/.cache/bazel
-    --without-embedded-docker  Enable docker client within container
+    --without-embedded-docker  Disable docker client within container
+    --verbose                  Enable verbose output
 
-environment variables (all optional):
-    WORKSPACE                    Set the path to the workspace (repo root)
-    AWS_ACCESS_KEY_ID            AWS auth token
-    AWS_SECRET_ACCESS_KEY        AWS auth token
-    BAZEL_STARTUP_ARGS           Additional startup arguments to pass to bazel invocations
-    BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
+Environment variables (all optional):
+    WORKSPACE                    Full path to the workspace (repo root)
+    EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
+
+Environment variables propagated into container:
+    BAZEL_STARTUP_ARGS
+    BAZEL_EXTRA_ARGS
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
@@ -90,6 +89,10 @@ while [[ $# -gt 0 ]]; do
       WITH_DOCKER_SOCK=0
       shift
       ;;
+    --verbose)
+      VERBOSE=1
+      shift
+      ;;
     -h | --help)
       usage 0
       break
@@ -106,34 +109,69 @@ if [[ -z ${IMAGE} ]]; then
   printf -- "error: --image must be specified\n" &>/dev/stderr
   usage 1
 fi
-readonly IMAGE_TAGGED=${IMAGE_LIST[${IMAGE}]}
-if [[ -z ${IMAGE_TAGGED} ]]; then
-  printf -- "error: image [%s] not recognized\n" "${IMAGE}" &>/dev/stderr
-  usage 1
+# shellcheck disable=SC2076
+if ! [[ " ${IMAGE_LIST[*]} " =~ " ${IMAGE} " ]]; then
+    printf -- "error: image [%s] not recognized\n" "${IMAGE}" &>/dev/stderr
+      usage 1
 fi
 
-SCRIPT_DIR="$(dirname $(readlink -f "$0"))"
+SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 WORKSPACE="${WORKSPACE-"$(readlink -f "${SCRIPT_DIR}"/../..)"}"
-readonly BUILDER_DIR="${WORKSPACE}/builders/${IMAGE}"
 
-# build container image and load it into the local docker client
-if ! docker image inspect ${IMAGE_TAGGED} &>/dev/null; then
-  tar --create --dereference --gzip --directory=${WORKSPACE}/builders/${IMAGE} . |
-  docker build - --tag ${IMAGE_TAGGED}
+# if running inside a docker container, the workspace mount point cannot be
+# determined by git or bazel or inspecting the filesystem itself. Instead, we
+# need to use docker to expose its mount info for the /src/workspace path.
+if [[ -f /.dockerenv ]]; then
+  # determine the current container's ID
+  CONTAINER_ID=$(uname --nodename)
+  # use docker inspect to extract the current mount path for /src/workspace
+  # this format string is a golang template (https://pkg.go.dev/text/template) processed
+  # by docker's --format flag, per https://docs.docker.com/config/formatting/
+  # shellcheck disable=SC2016
+  declare -r FORMAT_STR='
+    {{- range $v := .HostConfig.Binds -}}
+      {{$pathpair := split $v ":" -}}
+      {{if eq (index $pathpair 1) "/src/workspace" -}}
+        {{print (index $pathpair 0) -}}
+      {{end -}}
+    {{end -}}
+  '
+  WORKSPACE_MOUNT="$(docker inspect --format "${FORMAT_STR}" "${CONTAINER_ID}")"
+  readonly WORKSPACE_MOUNT
+  if [[ -z ${WORKSPACE_MOUNT} ]]; then
+    printf "Unable to determine mount point for /src/workspace. Exiting\n" &>/dev/stderr
+    exit 1
+  fi
+else
+  WORKSPACE_MOUNT="${WORKSPACE}"
 fi
+if [[ ${VERBOSE} -eq 1 ]]; then
+  printf "mounting workspace into container: %s\n" "${WORKSPACE_MOUNT}" &>/dev/stderr
+fi
+
+IMAGE_TAGGED="$("${WORKSPACE}"/builders/tools/get-builder-image-tagged --image "${IMAGE}")"
+readonly IMAGE_TAGGED
 
 declare -a DOCKER_RUN_ARGS
 DOCKER_RUN_ARGS+=(
   "--rm"
   "--entrypoint=/bin/bash"
-  "--volume ${WORKSPACE}:/src/workspace"
-  "--volume /dev/shm:/dev/shm"
+  "--volume ${WORKSPACE_MOUNT}:/src/workspace"
   "--workdir /src/workspace"
+  "${EXTRA_DOCKER_RUN_ARGS}"
 )
 
-if [[ ${WITH_SHARED_CACHE} -eq 1 ]]; then
+# inside the docker build images, /bazel_root is the bazel cache dir, per the system-wide bazelrc
+readonly BAZEL_ROOT=/bazel_root
+if [[ ${WITH_SHARED_CACHE} -eq 0 ]]; then
+  # use tmpfs for as temporary, container-bound bazel cache
   DOCKER_RUN_ARGS+=(
-    "--volume ${HOME}/.cache/bazel:/root/.cache/bazel"
+    "--tmpfs ${BAZEL_ROOT}:exec"
+  )
+else
+  # mount host filesystem for "shared" use by multiple docker container invocations
+  DOCKER_RUN_ARGS+=(
+    "--volume ${HOME}/.cache/bazel:${BAZEL_ROOT}"
   )
 fi
 if [[ ${WITH_DOCKER_SOCK} -eq 1 ]]; then
@@ -147,23 +185,26 @@ do
     "--env ${evar}"
   )
 done
-if [[ -t 1 ]]; then
-  # stdout is open, assume it's an interactive tty session
+if [[ -t 0 ]] && [[ -t 1 ]]; then
+  # stdin and stdout are open, assume it's an interactive tty session
   DOCKER_RUN_ARGS+=(
     "--interactive"
     "--tty"
   )
 fi
 
-set -o xtrace
+if [[ ${VERBOSE} -eq 1 ]]; then
+  set -o xtrace
+fi
 if [[ -z ${CMD} ]]; then
-  docker run \
-  ${DOCKER_RUN_ARGS[@]} \
-  ${IMAGE_TAGGED}
-else
-  printf "executing [%s] using image [%s]:\n\n" "${CMD}" "${IMAGE_TAGGED}" &>/dev/stderr
+  # shellcheck disable=SC2068
   docker run \
     ${DOCKER_RUN_ARGS[@]} \
-    ${IMAGE_TAGGED} \
+    "${IMAGE_TAGGED}"
+else
+  # shellcheck disable=SC2068
+  docker run \
+    ${DOCKER_RUN_ARGS[@]} \
+    "${IMAGE_TAGGED}" \
     -c "$CMD"
 fi
diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -17,36 +17,36 @@
 set -o pipefail
 set -o errexit
 set -o xtrace
-export PS4='+\t ' # xtrace prompt
+export TZ=Etc/UTC
+export PS4='+\tZ ' # xtrace prompt
 
 START=$(date +%s)
 
 trap _print_runtime EXIT
 
 function _print_runtime() {
-  local END=$(date +%s)
-  env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) > /dev/stderr
+  local STATUS=$?
+  local END
+  END=$(date +%s)
+  /usr/bin/env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) >/dev/stderr
+  # shellcheck disable=SC2086
+  exit ${STATUS}
 }
 
-CLEAN=0
-BUILD_AND_TEST_ALL_ARGS=
-PRESUBMIT=0
+VERBOSE=0
 PRECOMMIT_ONLY=0
+BUILD_AMI=0
 WITH_SHARED_CACHE=1
-WITH_DOCKER_SOCK=1
-readonly IMAGE_TAGGED=privacysandbox/builders/build-debian:bazel_build_image
 
-usage() {
+function usage() {
   local exitval=${1-1}
   cat >&2 << USAGE
 usage:
   $0 <options>
-    --without-shared-cache       Use a container-local cache
-    --without-embedded-docker    Enable docker client within container
+    --without-shared-cache       Containers will not mount ${HOME}/.cache/bazel
     --precommit-only             Run precommit then exit
-    --with-ami                   Build the AMI
-    --remove-output-base         Remove the bazel output-base dir after building
-    --clean                      Optionally clean build cache before running build
+    --with-ami                   Build the AMI. Default: false
+    --verbose                    Enable verbose output
 
 environment variables (all optional):
     WORKSPACE                    Set the path to the workspace (repo root)
@@ -54,6 +54,7 @@ environment variables (all optional):
     BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
     EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
 USAGE
+  # shellcheck disable=SC2086
   exit ${exitval}
 }
 
@@ -65,29 +66,22 @@ while [[ $# -gt 0 ]]; do
       ;;
     --without-shared-cache)
       WITH_SHARED_CACHE=0
-      shift
-      ;;
-    --without-embedded-docker)
-      WITH_DOCKER_SOCK=0
+      CBUILD_ARGS="--without-shared-cache"
       shift
       ;;
     --presubmit)
-      BUILD_AND_TEST_ALL_ARGS="${BUILD_AND_TEST_ALL_ARGS} $1"
-      PRESUBMIT=1
+      # no-op
       shift
       ;;
-    --with-ami | --remove-output-base)
-      BUILD_AND_TEST_ALL_ARGS="${BUILD_AND_TEST_ALL_ARGS} $1"
+    --with-ami)
+      BUILD_AMI=1
       shift
       ;;
-    --clean)
-      CLEAN=1
+    --verbose)
+      VERBOSE=1
       shift
       ;;
-    -h | --help)
-      usage 0
-      break
-      ;;
+    -h | --help) usage 0 ;;
     *)
       usage
       break
@@ -95,74 +89,60 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-function cbuild() {
-  declare -a EXTRA_DOCKER_ARGS
+SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+WORKSPACE="${WORKSPACE-"$(readlink -f "${SCRIPT_DIR}"/../..)"}"
+CBUILD="${WORKSPACE}"/builders/tools/cbuild
+export CBUILD_ARGS
 
-  # build container image and load it into the local docker client
-  if ! docker image inspect ${IMAGE_TAGGED} >/dev/null 2>&1; then
-    tar --create --dereference --gzip --directory=${WORKSPACE}/builders/build-debian . |
-    docker build - --tag ${IMAGE_TAGGED}
-  fi
-  if [[ ${WITH_DOCKER_SOCK} -eq 1 ]]; then
-    EXTRA_DOCKER_ARGS+=(
-      -v /var/run/docker.sock:/var/run/docker.sock
-    )
-  fi
-  if [[ ${WITH_SHARED_CACHE} -eq 1 ]]; then
-    EXTRA_DOCKER_ARGS+=(
-      -v "${HOME}/.cache/bazel:/root/.cache/bazel"
-    )
-  fi
-  if [[ -n ${AWS_ACCESS_KEY_ID} ]]; then
-    EXTRA_DOCKER_ARGS+=(
-      --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
-      --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
-    )
-  fi
-  if [[ -n ${BAZEL_EXTRA_ARGS} ]]; then
-    EXTRA_DOCKER_ARGS+=(
-      --env BAZEL_EXTRA_ARGS
-    )
-  fi
-  if [[ -n ${BAZEL_STARTUP_ARGS} ]]; then
-    EXTRA_DOCKER_ARGS+=(
-      --env BAZEL_STARTUP_ARGS
-    )
-  fi
-
-  if ! [[ -t 1 ]]; then
-    TTY_OUTPUT='| tail -f'
-  fi
-  docker run --rm \
-    --entrypoint=/bin/bash \
-    -v "${WORKSPACE}:/src/workspace" \
-    -w /src/workspace \
-    "${EXTRA_DOCKER_ARGS[@]}" \
-    ${EXTRA_DOCKER_RUN_ARGS} \
-    ${IMAGE_TAGGED} \
-    -c "$@ ${TTY_OUTPUT}"
-}
-
-WORKSPACE=${WORKSPACE-$(bazel info workspace)}
-
-if [[ ${CLEAN} -eq 1 ]]; then
-  cbuild "bazel clean --expunge_async ${BAZEL_ARGS}"
-  exit
+if [[ ${BUILD_AMI} -eq 1 ]]; then
+  BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --//:instance=aws --//:platform=aws"
+else
+  BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --//:instance=local --//:platform=aws"
 fi
 
-${WORKSPACE}/tools/pre-commit
+function _cbuild_debian() {
+  printf "=== cbuild debian action envs ===\n"
+  "${CBUILD}" ${CBUILD_ARGS} --image build-debian --cmd "grep -o 'action_env.*' /etc/bazel.bazelrc" 1>/dev/stderr 2>/dev/null
+  "${CBUILD}" ${CBUILD_ARGS} --image build-debian --cmd "$*"
+}
+
+if [[ ${VERBOSE} -eq 1 ]]; then
+  set -o xtrace
+  CBUILD_ARGS="${CBUILD_ARGS} --verbose"
+fi
+
+"${WORKSPACE}"/tools/pre-commit
 if [[ ${PRECOMMIT_ONLY} -eq 1 ]]; then
   exit 0
 fi
 
-cbuild "production/packaging/build_and_test_all ${BUILD_AND_TEST_ALL_ARGS}"
+printf "==== build and test specified targets using bazel-debian ====\n"
 
-if [[ ${PRESUBMIT} -eq 0 ]]; then
-  if [[ -d ${WORKSPACE}/dist ]]; then
-    cbuild "chgrp --recursive $(id -g) dist/ && chown --recursive $(id -u) dist/"
-    printf "location of the build artifacts:\n"
-    ls -lh ${WORKSPACE}/dist
-  else
-    printf "${WORKSPACE}/dist dir not found\n"
-  fi
+_cbuild_debian "
+trap _collect_logs EXIT
+function _collect_logs() {
+  local STATUS=$?
+  printf 'Collecting bazel logs...\n' &>/dev/stderr
+  bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //:collect-logs
+  # shellcheck disable=SC2086
+  exit ${STATUS}
+}
+set -o errexit
+bazel ${BAZEL_STARTUP_ARGS} build ${BAZEL_EXTRA_ARGS} //components/... //public/... //tools/...
+bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //production/packaging/aws/data_server:copy_to_dist
+bazel ${BAZEL_STARTUP_ARGS} test ${BAZEL_EXTRA_ARGS} //components/... //public/...
+"
+"${WORKSPACE}"/builders/tools/normalize-dist
+
+if [[ ${BUILD_AMI} -eq 1 ]]; then
+  EXTRA_ARGS="--with-ami"
+fi
+"${SCRIPT_DIR}"/aws/build_and_test --server-image dist/debian/server_docker_image.tar ${EXTRA_ARGS}
+
+DIST="${WORKSPACE}"/dist
+if [[ -d ${DIST} ]]; then
+  printf "build artifacts:\n"
+  ls -lhR "${DIST}"
+else
+  printf "dir not found: [%s]\n" "${DIST}"
 fi
