Release 0.5.0 (#21)
### Features

* Add basic smoke test
* Add builders/utils docker image
* Add hadolint to lint Dockerfiles
* Add toolchain short hash to bazel output_user_root path
* Add tools/lib/builder.sh
* Add utils for working with snapshot files.
* Adopt build-system release-0.2.0
* Allow AMI building to specify AWS region.
* Bump debian runtime to stable-20221004-slim
* Rename nitro_artifacts to aws_artifacts
* Set BUILD_ARCH env var in docker images
* Simplify use of --with-ami flag
* Tag small tests
* Upgrade build-debian to python3.9
* Upgrade to build-system 0.3.1
* Upgrade to build-system 0.4.3
* Upgrade to build-system 0.4.4
* Upgrade to clang v14 on bazel-debian

### Bug Fixes

* Add get_workspace_mount function to encapsulate code block
* Allow server script to accept any flags
* Avoid installing recommended debian packages
* Copy get_values_descriptor_set.pb to dist dir
* Correct shell quoting
* Correct workspace volume when tools/terraform is executed in a nested container
* Execute tests prior to copy_to_dist
* Guess user/group for files when running container as root bazel
* Ignore InvalidArgument error on completing lifecycle hook.
* include a backoff on errors to long poll 'push' notifications.
* Invoke addlicense for all text files
* Invoke unzip via utils image
* Migrate duration code into KV server.
* Minor improvements to shell scripts
* Modify normalize-dist to use builder::id function
* Mount $HOME/aws in aws-cli container
* Move builder-related configs to builders/etc
* Move WORKSPACE definition to cbuild script global
* multi-region support for sqs_lambda
* Propagate AWS env vars and $HOME/.aws into terraform container
* Propagate gcloud stderr
* Reduce noise from tools/collect-logs
* Remove build timestamp to afford stability of binary
* Remove debugging statement
* Remove docker flags -i and -t
* Remove dockerfile linter ignore and correct ENTRYPOINT
* Remove pre-commit config from build-debian
* Rename bazel image name debian-slim to runtime-debian
* Set architecture in container_image declaration
* Set bazel output_base to accommodate distinct workspaces
* Set WORKSPACE variable
* Support regions outside us-east-1
* unzip should overwrite files
* Update gazelle to v0.28.0
* Upgrade bazel-skylib to 1.3.0
* Upgrade rules_pkg to 0.8.0
* Use builder library functions

### Documentation

* Add error handling guidelines.
* Add submodule instructions
* Fix build command
* fix typo in aws doc
* recommend the use of native AWS CLI in documentation
* Remove an unnecessary step in server doc

Bug: 259086550
Change-Id: I32e29819d8f2b44ea4c03bb321d6210eb73d3137
GitOrigin-RevId: 74883e809ec655a5faf6f552f4bbf233431b7399

Co-authored-by: Privacy Sandbox Team <noreply@google.com>

diff --git a/builders/tools/get-architecture b/builders/tools/get-architecture
--- a/builders/tools/get-architecture
+++ b/builders/tools/get-architecture
@@ -15,4 +15,17 @@
 
 set -o errexit
 
-docker run --rm --entrypoint=/bin/bash ubuntu:20.04 -c "dpkg --print-architecture | tr -d '\n'"
+trap _cleanup EXIT
+function _cleanup() {
+  local -r -i STATUS=$?
+  if [[ ${STATUS} -ne 0 ]]; then
+    printf "Error: get-architecture status code: %s\n" "${STATUS}" &>/dev/stderr
+  fi
+  exit ${STATUS}
+}
+
+if [[ -n ${BUILD_ARCH} ]]; then
+  printf "%s\n" "${BUILD_ARCH}"
+else
+  docker run --rm --entrypoint=/usr/bin/dpkg ubuntu:20.04 --print-architecture
+fi
diff --git a/builders/tools/normalize-dist b/builders/tools/normalize-dist
--- a/builders/tools/normalize-dist
+++ b/builders/tools/normalize-dist
@@ -19,17 +19,34 @@
 set -o pipefail
 set -o errexit
 
-CBUILD="$(dirname "$(readlink -f "$0")")/cbuild"
-IMAGE=build-debian
-GROUP="$(id -g)"
-USER="$(id -u)"
+trap _cleanup EXIT
+function _cleanup() {
+  local -r -i STATUS=$?
+  if [[ ${STATUS} -eq 0 ]]; then
+    printf "normalize-dist completed successfully\n" &>/dev/stderr
+  else
+    printf "Error: normalize-dist completed with status code: %s\n" "${STATUS}" &>/dev/stderr
+  fi
+  exit 0
+}
 
-TOP_LEVEL_DIRS="dist"
+TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+readonly TOOLS_DIR
+# shellcheck disable=SC1091
+source "${TOOLS_DIR}"/builder.sh
+readonly IMAGE=build-debian
+GROUP="$(builder::id g)"
+readonly GROUP
+USER="$(builder::id u)"
+readonly USER
+
+readonly TOP_LEVEL_DIRS="dist"
 
 printf "Setting file ownership [%s], group [%s] in dirs [%s]\n" "${USER}" "${GROUP}" "${TOP_LEVEL_DIRS}"
-"${CBUILD}" --image ${IMAGE} --cmd "
+"${TOOLS_DIR}"/cbuild --image ${IMAGE} --cmd "
 for TOP_LEVEL_DIR in ${TOP_LEVEL_DIRS}; do
-  find \${TOP_LEVEL_DIR} -type f -exec chmod 644 {} \;
+  find \${TOP_LEVEL_DIR} -type f ! -executable -exec chmod 644 {} \;
+  find \${TOP_LEVEL_DIR} -type f -executable -exec chmod 755 {} \;
   find \${TOP_LEVEL_DIR} -type d -exec chmod 755 {} \;
   chgrp --recursive ${GROUP} \${TOP_LEVEL_DIR}
   chown --recursive ${USER} \${TOP_LEVEL_DIR}
diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -13,39 +13,41 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-
 set -o pipefail
 set -o errexit
-set -o xtrace
 export TZ=Etc/UTC
-export PS4='+\tZ ' # xtrace prompt
+export PS4='+\t $(basename ${BASH_SOURCE[0]}):${LINENO} ' # xtrace prompt
 
 START=$(date +%s)
+readonly START
 
 trap _print_runtime EXIT
-
 function _print_runtime() {
-  local STATUS=$?
-  local END
-  END=$(date +%s)
-  /usr/bin/env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) >/dev/stderr
-  # shellcheck disable=SC2086
+  local -r -i STATUS=$?
+  local -r -i END=$(date +%s)
+  /usr/bin/env LC_ALL=en_US.UTF-8 printf "\nbuild_and_test_all_in_docker runtime: %'ds\n" $((END - START)) &>/dev/stderr
+  if [[ ${STATUS} -eq 0 ]]; then
+    printf "build_and_test_in_docker completed successfully\n" &>/dev/stderr
+  else
+    printf "Error: build_and_test_in_docker completed with status code: %s\n" "${STATUS}" &>/dev/stderr
+  fi
   exit ${STATUS}
 }
 
 VERBOSE=0
+VERBOSE_ARG=
 PRECOMMIT_ONLY=0
-BUILD_AMI=0
-WITH_SHARED_CACHE=1
+declare -a AMI_REGIONS
 
 function usage() {
-  local exitval=${1-1}
-  cat >&2 << USAGE
+  local -r -i exitval=${1-1}
+  cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
     --without-shared-cache       Containers will not mount ${HOME}/.cache/bazel
     --precommit-only             Run precommit then exit
-    --with-ami                   Build the AMI. Default: false
+    --with-ami                   AMI region in which to build and store AWS AMIs. Use multiple times to specify more than one region
+                                 If empty, none will be built
     --verbose                    Enable verbose output
 
 environment variables (all optional):
@@ -65,8 +67,8 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     --without-shared-cache)
-      WITH_SHARED_CACHE=0
       CBUILD_ARGS="--without-shared-cache"
+      export CBUILD_ARGS
       shift
       ;;
     --presubmit)
@@ -74,7 +76,8 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     --with-ami)
-      BUILD_AMI=1
+      AMI_REGIONS+=("$2")
+      shift
       shift
       ;;
     --verbose)
@@ -89,55 +92,50 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
-WORKSPACE="${WORKSPACE-"$(readlink -f "${SCRIPT_DIR}"/../..)"}"
-CBUILD="${WORKSPACE}"/builders/tools/cbuild
-export CBUILD_ARGS
+SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+# shellcheck source=builders/tools/builder.sh
+source "${SCRIPT_DIR}"/../../builders/tools/builder.sh
 
-if [[ ${BUILD_AMI} -eq 1 ]]; then
+if [[ -n ${AMI_REGIONS[0]} ]]; then
   BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --//:instance=aws --//:platform=aws"
 else
   BAZEL_EXTRA_ARGS="${BAZEL_EXTRA_ARGS} --//:instance=local --//:platform=aws"
 fi
 
-function _cbuild_debian() {
-  printf "=== cbuild debian action envs ===\n"
-  "${CBUILD}" ${CBUILD_ARGS} --image build-debian --cmd "grep -o 'action_env.*' /etc/bazel.bazelrc" 1>/dev/stderr 2>/dev/null
-  "${CBUILD}" ${CBUILD_ARGS} --image build-debian --cmd "$*"
-}
-
 if [[ ${VERBOSE} -eq 1 ]]; then
   set -o xtrace
+  VERBOSE_ARG="--verbose"
   CBUILD_ARGS="${CBUILD_ARGS} --verbose"
 fi
 
-"${WORKSPACE}"/tools/pre-commit
+"${WORKSPACE}"/builders/tools/pre-commit
 if [[ ${PRECOMMIT_ONLY} -eq 1 ]]; then
   exit 0
 fi
 
 printf "==== build and test specified targets using bazel-debian ====\n"
 
-_cbuild_debian "
+builder::cbuild_debian "
 trap _collect_logs EXIT
 function _collect_logs() {
-  local STATUS=$?
+  local -r -i STATUS=\$?
   printf 'Collecting bazel logs...\n' &>/dev/stderr
   bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //:collect-logs
-  # shellcheck disable=SC2086
-  exit ${STATUS}
+  exit \${STATUS}
 }
 set -o errexit
 bazel ${BAZEL_STARTUP_ARGS} build ${BAZEL_EXTRA_ARGS} //components/... //public/... //tools/...
+bazel ${BAZEL_STARTUP_ARGS} test ${BAZEL_EXTRA_ARGS} --test_size_filters=small //...
 bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //production/packaging/aws/data_server:copy_to_dist
-bazel ${BAZEL_STARTUP_ARGS} test ${BAZEL_EXTRA_ARGS} //components/... //public/...
 "
-"${WORKSPACE}"/builders/tools/normalize-dist
 
-if [[ ${BUILD_AMI} -eq 1 ]]; then
-  EXTRA_ARGS="--with-ami"
+if [[ -n ${AMI_REGIONS[0]} ]]; then
+  printf -v EXTRA_ARGS -- '--with-ami %s ' "${AMI_REGIONS[@]}"
+  if [[ ${VERBOSE} -eq 1 ]]; then
+    EXTRA_ARGS="${EXTRA_ARGS} --verbose"
+  fi
 fi
-"${SCRIPT_DIR}"/aws/build_and_test --server-image dist/debian/server_docker_image.tar ${EXTRA_ARGS}
+"${SCRIPT_DIR}"/aws/build_and_test ${VERBOSE_ARG} --server-image dist/debian/server_docker_image.tar ${EXTRA_ARGS}
 
 DIST="${WORKSPACE}"/dist
 if [[ -d ${DIST} ]]; then
