Release 0.11.0 (2023-07-11)
### Features

* [Breaking change] Use UserDefinedFunctionsConfig instead of KVs for loading UDFs.
* [Sharding] Add hpke for s2s communication
* [Sharding] Allow for partial data lookups
* [Sharding] Making downstream requests in parallel
* Add bazel build flag --announce_rc
* Add bool parameter to allow routing V1 requests through V2.
* Add buf format pre-commit hook
* Add build time directive for reentrant parser.
* Add functions to retrieve instance information.
* Add internal run query client and server.
* Add JS hook for set query.
* Add lookup client and server for communication with shards
* Add MessageQueue for the request simulation system
* Add query grammar and interface for set queries.
* Add rate limiter for the request simulation system
* Add second map to store key value set and add set value update interfaces
* Add shard metadata for supporting sharded files
* Add simple microbenchmarks for key value cache
* Add UDF support for format data command.
* Add unit tests for query lexer.
* Adding cluster mappings manager
* Adding padding
* Apply custom lockings on the cache
* Connect InternalRunQuery to the parser
* Extend and simplify collect-logs to capture test outputs
* Extend use of scp deps via data-plane-shared repo
* Implement shard manager
* Move sharding function to public so it's available for file sharding
* Register a logging hook with the UDF.
* Register run query hook with udf framework.
* Sharding - realtime updates
* Sharding read flow fixes
* Simplify work done in set operations. Set operations can be passed by
* Snapshot files support UDF configs.
* Support reading and writing set queries to data files.
* Support reading and writing set values for csv files
* Support reading/writing DataRecords. Requires new DELTA format.
* Support writing sharded files
* Update data_loading.fb to support UDF code updates.
* Update pre-commit hook versions
* Update shard manager mappings continuously
* Upgrade build-system to release-0.28.0
* Upgrade build-system to v0.30.1
* Upgrade scp to 0.72.0
* Use Unix domain socket for internal lookup server.
* Utilize AWS deps via data-plane-shared repo

### Bug Fixes

* Add internal lookup client deadline.
* Catch error if insufficient args specified
* Fix aggregation logic for set values.
* Fix ASAN potential deadlock errors in key_value_cache_test
* Proper memory management of callback hook wrappers.
* Specify 2 workers for UDF execution.
* Upgrade pre-commit hooks
* Use shared pointer for UDF absl::Notification.

### Build Tools: Fixes

* **build:** Add scope-based sections in release notes

### Documentation

* Add docs for data loading capabilities
* Add explanation that access control is managed by IAM for writes.
* Point readme to a new sharding public explainer

Bug: 290798418
Change-Id: I691da695f5727a8517ed3e9f18a3a2d8c5b9e0bf
GitOrigin-RevId: 5958051464911b6da60c38bc2a83c3451adadf42

diff --git a/builders/tools/get-builder-image-tagged b/builders/tools/get-builder-image-tagged
--- a/builders/tools/get-builder-image-tagged
+++ b/builders/tools/get-builder-image-tagged
@@ -23,9 +23,6 @@ set -o errexit
 trap _cleanup EXIT
 function _cleanup() {
   declare -r -i STATUS=$?
-  if [[ -n ${TAR_IMAGE} ]]; then
-    docker image rm --force "${TAR_IMAGE}" &>/dev/null
-  fi
   if [[ -n ${TEMPTAR} ]]; then
     rm -f "${TEMPTAR}" "${SHAFILE}"
   fi
@@ -66,23 +63,20 @@ function usage() {
   cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
-    --no-build            Do not build image if it doesn't exist
-    --image               Image name for the build runtime. Valid names:
-
-environment variables (all optional):
-    IMAGE_BUILD_VERBOSE   Capture docker build output if set
+    --no-build     Do not build image if it doesn't exist
+    --image        Image name for the build runtime. Valid names:
 USAGE
 
   for elem in $(get_image_list "${IMAGES_DIR}"); do
-    if [[ ${IMAGE} == "${elem}" ]]; then
-      local EXTRA=" (default)"
-    fi
-    printf "                       *  %s%s\n" "${elem}" "${EXTRA}" &>/dev/stderr
+    printf "                       *  %s\n" "${elem}" &>/dev/stderr
   done
 
   cat &>/dev/stderr <<USAGE
     --sha-only     Emit only the SHA rather than the image name
     --verbose      Enable verbose output
+
+environment variables (all optional):
+    IMAGE_BUILD_VERBOSE   Capture docker build output if set
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
@@ -90,8 +84,9 @@ USAGE
 
 TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 readonly TOOLS_DIR
-readonly ETC_DIR="${TOOLS_DIR}"/../etc
-readonly IMAGES_DIR="${TOOLS_DIR}"/../images
+readonly BUILDERS_DIR="${TOOLS_DIR}"/..
+readonly ETC_DIR="${BUILDERS_DIR}"/etc
+readonly IMAGES_DIR="${BUILDERS_DIR}"/images
 declare -i SHA_ONLY=0
 declare -i BUILD_IMAGE_IF_NEEDED=1
 declare -i VERBOSE=0
@@ -99,7 +94,7 @@ declare -r -a DOCKER_BUILD_ARGS=(
   --progress plain
 )
 
-# shellcheck disable=SC1091
+# shellcheck disable=SC1090
 source "${TOOLS_DIR}"/builder.sh
 WORKSPACE_MOUNT="$(builder::get_docker_workspace_mount)"
 readonly WORKSPACE_MOUNT
@@ -151,20 +146,30 @@ if ! [[ -s ${IMAGE_PATH_FULL}/Dockerfile ]]; then
   exit 1
 fi
 
-# install gnu tar into a docker image
-readonly TAR_IMAGE="builders/tar-get-builder-image-tagged:pid-$$"
-BUILD_OUTPUT="$(make_temp .log)"
-readonly BUILD_OUTPUT
-{
-  cat <<Dockerfile
+# create an image containing gnu tar
+function generate_image() {
+  {
+    cat <<Dockerfile
 FROM alpine:3.16
 RUN apk --no-cache add tar~=1.34
 Dockerfile
-} | docker buildx build "${DOCKER_BUILD_ARGS[@]}" --no-cache --output=type=docker --tag "${TAR_IMAGE}" - &>"${BUILD_OUTPUT}"
-rm -f "${BUILD_OUTPUT}"
-if ! docker image inspect "${TAR_IMAGE}" &>/dev/null; then
-  printf "error creating docker image [%s]\n" "${TAR_IMAGE}" &>/dev/stderr
-  exit 1
+  } | docker buildx build "${DOCKER_BUILD_ARGS[@]}" --no-cache --output=type=docker --tag "${TAR_IMAGE}" - &>"${BUILD_OUTPUT}"
+  rm -f "${BUILD_OUTPUT}"
+  if ! docker image inspect "${TAR_IMAGE}" &>/dev/null; then
+    printf "error creating docker image [%s]\n" "${TAR_IMAGE}" &>/dev/stderr
+    exit 1
+  fi
+}
+
+BUILD_OUTPUT="$(make_temp .log)"
+readonly BUILD_OUTPUT
+BUILDSYS_VERSION="$(<"${BUILDERS_DIR}"/version.txt)"
+readonly BUILDSYS_VERSION
+readonly TAR_IMAGE="builders/tar-get-builder-image-tagged:v${BUILDSYS_VERSION}"
+TAR_IMAGE_HASH="$(docker image ls --filter "reference=${TAR_IMAGE}" --quiet)"
+readonly TAR_IMAGE_HASH
+if [[ -z ${TAR_IMAGE_HASH} ]]; then
+  generate_image
 fi
 
 # Create a deterministic tar file for the specified file path, returning
@@ -182,19 +187,20 @@ function _tar_for_dir() {
   # expand TMP_IMAGE_DIR immediately
   trap "rm -rf '${TMP_IMAGE_DIR}'" RETURN
 
-  WS_FILE_TAR="$(realpath "${FILE_TAR}" --relative-to="${WORKSPACE}")"
-  WS_FILE_SHA="$(realpath "${FILE_SHA}" --relative-to="${WORKSPACE}")"
-  WS_FILEPATH="$(realpath "${FILEPATH}" --relative-to="${WORKSPACE}")"
-  WS_TMP_IMAGE_DIR="$(realpath "${TMP_IMAGE_DIR}" --relative-to="${WORKSPACE}")"
+  local -r WS_FILE_TAR="$(realpath "${FILE_TAR}" --relative-to="${WORKSPACE}")"
+  local -r WS_FILE_SHA="$(realpath "${FILE_SHA}" --relative-to="${WORKSPACE}")"
+  local -r WS_FILEPATH="$(realpath "${FILEPATH}" --relative-to="${WORKSPACE}")"
+  local -r WS_TMP_IMAGE_DIR="$(realpath "${TMP_IMAGE_DIR}" --relative-to="${WORKSPACE}")"
   # find workspace etc files that are also in the image dir and the builders etc dir
-  WORKSPACE_ETC_FILES="$({
+  local -r WORKSPACE_ETC_FILES="$({
     # shellcheck disable=SC2012
     ls -A -1 "${FILEPATH}" "${ETC_DIR}" | sort | uniq -d
     ls -A -1 "${WORKSPACE}"
   } | sort | uniq -d)"
   # create a deterministic tarball of the collected files
-  docker run --rm \
-    --entrypoint=/bin/sh \
+  docker run \
+    --rm \
+    --entrypoint /bin/sh \
     --volume "${WORKSPACE_MOUNT}":/workspace \
     --workdir /workspace \
     "${TAR_IMAGE}" -c "
@@ -218,13 +224,13 @@ tar --create --dereference --sort=name --owner=0 --group=0 --numeric-owner --for
 "
 }
 
-TEMPTAR="$(make_temp .tar.gz)"
+TEMPTAR="$(make_temp .tar)"
 readonly TEMPTAR
 SHAFILE="$(make_temp .sha)"
 readonly SHAFILE
 # use the tarfile size and file content to generate a sha256 hash
 _tar_for_dir "${TEMPTAR}" "${SHAFILE}" "${IMAGE_PATH_FULL}"
-SHA="$(cat "${SHAFILE}")"
+SHA="$(<"${SHAFILE}")"
 readonly SHA
 ARCH="$("${TOOLS_DIR}"/get-architecture)"
 readonly ARCH
diff --git a/production/packaging/aws/build_and_test b/production/packaging/aws/build_and_test
--- a/production/packaging/aws/build_and_test
+++ b/production/packaging/aws/build_and_test
@@ -60,8 +60,7 @@ while [[ $# -gt 0 ]]; do
   case "$1" in
     --with-ami)
       AMI_REGIONS+=("$2")
-      shift
-      shift
+      shift 2 || usage
       ;;
     --no-precommit)
       BUILD_AND_TEST_ARGS+=("--no-precommit")
@@ -72,14 +71,8 @@ while [[ $# -gt 0 ]]; do
       set -o xtrace
       shift
       ;;
-    -h | --help)
-      usage 0
-      break
-      ;;
-    *)
-      usage
-      break
-      ;;
+    -h | --help) usage 0 ;;
+    *) usage ;;
   esac
 done
 
@@ -89,14 +82,36 @@ function arr_to_string_list() {
   printf "[%s]" "${joined%,}"
 }
 
-SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
-readonly SCRIPT_DIR
+# Exit 1 on any error before pushing to origin.
+function fail() {
+  printf "\n\n[ERROR]: Failure: %s\n\n" "$@"
+  sleep 5s  # Make sure that stdout has time to be written
+  exit 1
+}
+
+printf "==== Sourcing builder.sh =====\n"
+# We can't use $WORKSPACE here as it may not be set - it'll be created
+# by builder.sh if it's empty.
+readonly SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+readonly BUILDER="${SCRIPT_DIR}"/../../../builders/tools/builder.sh
+if [[ ! -f ${BUILDER} ]]; then
+  ERROR_MESSAGE=$(printf "builder.sh file does not exist, expected at: %s\n"  "${BUILDER}")
+  fail "$ERROR_MESSAGE"
+fi
 # shellcheck source=builders/tools/builder.sh
-source "${SCRIPT_DIR}"/../../../builders/tools/builder.sh
+source "${BUILDER}" || fail "Failed to source builder.sh"
 readonly DIST="${WORKSPACE}"/dist
 
-"${WORKSPACE}"/production/packaging/build_and_test_all_in_docker "${BUILD_AND_TEST_ARGS[@]}" --instance aws
+printf "==== Running build_and_test_all_in_docker =====\n"
+if ! [[ -r ${WORKSPACE}/production/packaging/build_and_test_all_in_docker && -x ${WORKSPACE}/production/packaging/build_and_test_all_in_docker ]]; then
+  printf "build_and_test script not found at location: %s/production/packaging/build_and_test_all_in_docker\n" "${WORKSPACE}" &>/dev/stderr
+  fail "build_and_test not found"
+fi
+if ! "${WORKSPACE}"/production/packaging/build_and_test_all_in_docker "${BUILD_AND_TEST_ARGS[@]}" --instance aws; then
+  fail "Failed to run build_and_test_all_in_docker"
+fi
 
+printf "==== Creating dist dir =====\n"
 mkdir -p "${DIST}"/aws
 chmod 770 "${DIST}" "${DIST}"/aws
 
@@ -121,8 +136,9 @@ jq --compact-output --raw-output '.Measurements.PCR0' dist/aws/server_enclave_im
 cat dist/aws/pcr0.json
 exit 0
 "
-docker image rm --force ${IMAGE_URI}:"${IMAGE_TAG}"
+docker image rm --force ${IMAGE_URI}:"${IMAGE_TAG}" || fail "Unable to remove Docker image"
 
+printf "==== Checking PCR0 =====\n"
 readonly PCR0_REL_DIR=production/packaging/aws/data_server/nitro-pcr0
 readonly PCR0_DIR="${WORKSPACE}"/${PCR0_REL_DIR}
 readonly PCR0_FILE="${PCR0_DIR}"/${BUILD_ARCH}.json
@@ -141,6 +157,7 @@ else
   cat "${PCR0_FILE}"
 fi
 
+printf "==== Copying to dist =====\n"
 builder::cbuild_al2 $"
 trap _collect_logs EXIT
 function _collect_logs() {
@@ -152,7 +169,13 @@ function _collect_logs() {
 set -o errexit
 bazel ${BAZEL_STARTUP_ARGS} run ${BAZEL_EXTRA_ARGS} //production/packaging/aws/data_server/ami:copy_to_dist
 "
-"${WORKSPACE}"/builders/tools/normalize-dist
+
+printf "==== Running normalize_dist.sh =====\n"
+if ! [[ -r ${WORKSPACE}/builders/tools/normalize-dist && -x ${WORKSPACE}/builders/tools/normalize-dist ]]; then
+  printf "normalize_dist.sh file does not exist, expected at: %s/builders/tools/normalize-dist\n"  "${WORKSPACE}" &>/dev/stderr
+  fail "normalize_dist.sh does not exist"
+fi
+"${WORKSPACE}"/builders/tools/normalize-dist || { fail "Unable to run normalize-dist"; }
 
 if [[ -n ${AMI_REGIONS[0]} ]]; then
   UTILS_IMAGE="$("${WORKSPACE}"/builders/tools/get-builder-image-tagged --image utils)"
