Release 0.5.1 (#23)
### Bug Fixes

* Ignore builders/ when executing pre-commit
* Upgrade to build-system 0.5.0

Bug: NA
Change-Id: I2ab8d740f2ee3942d63b4c9423cf15c587323ca9
GitOrigin-RevId: 131e4d75da35458749b7a0f67eb7465678b9c111

Co-authored-by: Privacy Sandbox Team <no-reply@google.com>

diff --git a/builders/tools/get-builder-image-tagged b/builders/tools/get-builder-image-tagged
--- a/builders/tools/get-builder-image-tagged
+++ b/builders/tools/get-builder-image-tagged
@@ -38,13 +38,20 @@ function _cleanup() {
   exit ${STATUS}
 }
 
-declare -r -A IMAGE_NAMES=(
-  [build-debian]="privacysandbox/builders/build-debian"
-  [build-amazonlinux2]="privacysandbox/builders/build-amazonlinux2"
-  [presubmit]="privacysandbox/builders/presubmit"
-  [release]="privacysandbox/builders/release"
-  [utils]="privacysandbox/builders/utils"
-)
+function get_image_list() {
+  declare -r _images_dir="$1"
+  find "${_images_dir}" -maxdepth 1 -mindepth 1 -type d -printf "%P\n" | sort
+}
+
+function get_image_fullname() {
+  declare -r _img="$1"
+  declare -r _image_name=privacysandbox/builders/${_img}
+  if [[ -z ${_image_name} ]]; then
+    printf -- "error: image [%s] not recognized\n" "${_img}" &>/dev/stderr
+    return 1
+  fi
+  printf "%s" "${_image_name}"
+}
 
 function usage() {
   declare -r -i exitval=${1-1}
@@ -55,7 +62,7 @@ usage:
     --image              Image name for the build runtime. Valid names:
 USAGE
 
-  for elem in "${!IMAGE_NAMES[@]}"
+  for elem in $(get_image_list "${IMAGES_DIR}")
   do
     if [[ ${IMAGE} == "${elem}" ]]; then
       local EXTRA=" (default)"
@@ -69,6 +76,15 @@ USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
+
+TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+readonly TOOLS_DIR
+readonly ETC_DIR="${TOOLS_DIR}"/../etc
+readonly IMAGES_DIR="${TOOLS_DIR}"/../images
+# shellcheck disable=SC1091
+source "${TOOLS_DIR}"/builder.sh
+WORKSPACE_MOUNT="$(builder::get_docker_workspace_mount)"
+readonly WORKSPACE_MOUNT
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -94,25 +110,15 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-readonly TOOLS_DIR
-readonly ETC_DIR="${TOOLS_DIR}"/../etc
-readonly IMAGES_DIR="${TOOLS_DIR}"/../images
-# shellcheck disable=SC1091
-source "${TOOLS_DIR}"/builder.sh
-WORKSPACE_MOUNT="$(builder::get_docker_workspace_mount)"
-readonly WORKSPACE_MOUNT
-
 if [[ -z ${IMG} ]]; then
   printf -- "error: --image must be specified\n" &>/dev/stderr
   usage 1
 fi
 
-readonly IMAGE_NAME=${IMAGE_NAMES[${IMG}]}
-if [[ -z ${IMAGE_NAME} ]]; then
-  printf -- "error: image [%s] not recognized\n" "${IMG}" &>/dev/stderr
+if ! IMAGE_NAME="$(get_image_fullname "${IMG}")"; then
   usage 1
 fi
+readonly IMAGE_NAME
 
 IMAGE_PATH_FULL="${IMAGES_DIR}/${IMG}"
 if ! [[ -s ${IMAGE_PATH_FULL}/Dockerfile ]]; then
@@ -122,12 +128,13 @@ fi
 
 # install gnu tar into a docker image
 readonly TAR_IMAGE="builders/tar-get-builder-image-tagged:pid-$$"
+# shellcheck disable=SC2086
 {
   cat <<Dockerfile
 FROM alpine:3.16
 RUN apk --no-cache add tar=1.34-r0
 Dockerfile
-} | docker buildx build ${DOCKER_BUILD_ARGS} --output=type=docker --tag "${TAR_IMAGE}" - >/dev/null
+} | docker buildx build ${DOCKER_BUILD_ARGS} --no-cache --output=type=docker --tag "${TAR_IMAGE}" - >/dev/null
 if ! docker image inspect "${TAR_IMAGE}" &>/dev/null; then
   printf "error creating docker image [%s]\n" "${TAR_IMAGE}" &>/dev/stderr
   exit 1
@@ -194,6 +201,7 @@ if [[ ${BUILD_IMAGE_IF_NEEDED} -eq 1 ]]; then
   # build container image and load it into the local docker client
   if ! docker image inspect "${IMAGE_TAGGED}" &>/dev/null; then
     printf "generating docker image %s\n" "${IMAGE_TAGGED}" &>/dev/stderr
+    # shellcheck disable=SC2086
     docker buildx build ${DOCKER_BUILD_ARGS} --output=type=docker --tag "${IMAGE_TAGGED}" - <"${TEMPTAR}" &>/dev/stderr
   fi
 fi
