Release 0.5.0
### Features

* Add basic smoke test
* Add builders/utils docker image
* Add hadolint to lint Dockerfiles
* Add toolchain short hash to bazel output_user_root path
* Add tools/lib/builder.sh
* Add utils for working with snapshot files.
* Adopt build-system release-0.2.0
* Allow AMI building to specify AWS region.
* Bump debian runtime to stable-20221004-slim
* Rename nitro_artifacts to aws_artifacts
* Set BUILD_ARCH env var in docker images
* Simplify use of --with-ami flag
* Tag small tests
* Upgrade build-debian to python3.9
* Upgrade to build-system 0.3.1
* Upgrade to build-system 0.4.3
* Upgrade to build-system 0.4.4
* Upgrade to clang v14 on bazel-debian

### Bug Fixes

* Add get_workspace_mount function to encapsulate code block
* Allow server script to accept any flags
* Avoid installing recommended debian packages
* Copy get_values_descriptor_set.pb to dist dir
* Correct shell quoting
* Correct workspace volume when tools/terraform is executed in a nested container
* Execute tests prior to copy_to_dist
* Guess user/group for files when running container as root bazel
* Ignore InvalidArgument error on completing lifecycle hook.
* include a backoff on errors to long poll 'push' notifications.
* Invoke addlicense for all text files
* Invoke unzip via utils image
* Migrate duration code into KV server.
* Minor improvements to shell scripts
* Modify normalize-dist to use builder::id function
* Mount $HOME/aws in aws-cli container
* Move builder-related configs to builders/etc
* Move WORKSPACE definition to cbuild script global
* multi-region support for sqs_lambda
* Propagate AWS env vars and $HOME/.aws into terraform container
* Propagate gcloud stderr
* Reduce noise from tools/collect-logs
* Remove build timestamp to afford stability of binary
* Remove debugging statement
* Remove docker flags -i and -t
* Remove dockerfile linter ignore and correct ENTRYPOINT
* Remove pre-commit config from build-debian
* Rename bazel image name debian-slim to runtime-debian
* Set architecture in container_image declaration
* Set bazel output_base to accommodate distinct workspaces
* Set WORKSPACE variable
* Support regions outside us-east-1
* unzip should overwrite files
* Update gazelle to v0.28.0
* Upgrade bazel-skylib to 1.3.0
* Upgrade rules_pkg to 0.8.0
* Use builder library functions

### Documentation

* Add error handling guidelines.
* Add submodule instructions
* Fix build command
* fix typo in aws doc
* recommend the use of native AWS CLI in documentation
* Remove an unnecessary step in server doc

Bug: 259086550
Change-Id: I32e29819d8f2b44ea4c03bb321d6210eb73d3137
GitOrigin-RevId: 74883e809ec655a5faf6f552f4bbf233431b7399

diff --git a/builders/tools/get-builder-image-tagged b/builders/tools/get-builder-image-tagged
--- a/builders/tools/get-builder-image-tagged
+++ b/builders/tools/get-builder-image-tagged
@@ -20,26 +20,35 @@
 set -o pipefail
 set -o errexit
 
-VERBOSE=0
 BUILD_IMAGE_IF_NEEDED=1
+DOCKER_BUILD_ARGS="--quiet"
 
-declare -r -A IMAGE_DIRS=(
-  [build-debian]="builders/build-debian"
-  [build-amazonlinux2]="builders/build-amazonlinux2"
-  [presubmit]="builders/presubmit"
-  [release]="builders/release"
-)
+trap _cleanup EXIT
+function _cleanup() {
+  declare -r -i STATUS=$?
+  if [[ -n ${TAR_IMAGE} ]]; then
+    docker image rm --force "${TAR_IMAGE}" &>/dev/null
+  fi
+  if [[ -n ${TEMPTAR} ]]; then
+    rm -f "${TEMPTAR}" "${SHAFILE}"
+  fi
+  if [[ ${STATUS} -ne 0 ]]; then
+    printf "Error: get-builder-image-tagged status code: %d\n" ${STATUS} &>/dev/stderr
+  fi
+  exit ${STATUS}
+}
 
 declare -r -A IMAGE_NAMES=(
   [build-debian]="privacysandbox/builders/build-debian"
   [build-amazonlinux2]="privacysandbox/builders/build-amazonlinux2"
   [presubmit]="privacysandbox/builders/presubmit"
   [release]="privacysandbox/builders/release"
+  [utils]="privacysandbox/builders/utils"
 )
 
-usage() {
-  local exitval=${1-1}
-  cat &>/dev/stderr << USAGE
+function usage() {
+  declare -r -i exitval=${1-1}
+  cat &>/dev/stderr <<USAGE
 usage:
   $0 <options>
     --no-build           Do not build image if it doesn't exist
@@ -54,11 +63,8 @@ USAGE
     printf "                             *  %s%s\n" "${elem}" "${EXTRA}" &>/dev/stderr
   done
 
-  cat &>/dev/stderr << USAGE
+  cat &>/dev/stderr <<USAGE
     --verbose            Enable verbose output
-
-Environment variables (all optional):
-    WORKSPACE            Full path to the workspace (repo root)
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
@@ -76,7 +82,8 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     --verbose)
-      VERBOSE=1
+      DOCKER_BUILD_ARGS="--progress plain"
+      set -o xtrace
       shift
       ;;
     -h | --help) usage 0 ;;
@@ -87,50 +94,99 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
-WORKSPACE="${WORKSPACE-"$(readlink -f "${SCRIPT_DIR}"/../..)"}"
+TOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+readonly TOOLS_DIR
+readonly ETC_DIR="${TOOLS_DIR}"/../etc
+readonly IMAGES_DIR="${TOOLS_DIR}"/../images
+# shellcheck disable=SC1091
+source "${TOOLS_DIR}"/builder.sh
+WORKSPACE_MOUNT="$(builder::get_docker_workspace_mount)"
+readonly WORKSPACE_MOUNT
 
 if [[ -z ${IMG} ]]; then
   printf -- "error: --image must be specified\n" &>/dev/stderr
   usage 1
 fi
 
-readonly IMAGE_DIR=${IMAGE_DIRS[${IMG}]}
 readonly IMAGE_NAME=${IMAGE_NAMES[${IMG}]}
-if [[ -z ${IMAGE_NAME} ]] || [[ -z ${IMAGE_DIR} ]]; then
+if [[ -z ${IMAGE_NAME} ]]; then
   printf -- "error: image [%s] not recognized\n" "${IMG}" &>/dev/stderr
   usage 1
 fi
 
-DIR_FULL="${WORKSPACE}/${IMAGE_DIR}"
-
-if ! [[ -s ${DIR_FULL}/Dockerfile ]]; then
-  printf "error: unable to locate [%s/Dockerfile]\n" "${DIR_FULL}" &>/dev/stderr
+IMAGE_PATH_FULL="${IMAGES_DIR}/${IMG}"
+if ! [[ -s ${IMAGE_PATH_FULL}/Dockerfile ]]; then
+  printf "error: unable to locate [%s/Dockerfile]\n" "${IMAGE_PATH_FULL}" &>/dev/stderr
   exit 1
 fi
-TEMPTAR="$(mktemp --dry-run --suffix=.tar.gz)"
-readonly TEMPTAR
 
-trap _cleanup EXIT
+# install gnu tar into a docker image
+readonly TAR_IMAGE="builders/tar-get-builder-image-tagged:pid-$$"
+{
+  cat <<Dockerfile
+FROM alpine:3.16
+RUN apk --no-cache add tar=1.34-r0
+Dockerfile
+} | docker buildx build ${DOCKER_BUILD_ARGS} --output=type=docker --tag "${TAR_IMAGE}" - >/dev/null
+if ! docker image inspect "${TAR_IMAGE}" &>/dev/null; then
+  printf "error creating docker image [%s]\n" "${TAR_IMAGE}" &>/dev/stderr
+  exit 1
+fi
 
-function _cleanup() {
-  local STATUS=$?
-  rm -f "${TEMPTAR}"
-  # shellcheck disable=SC2086
-  exit ${STATUS}
+# Create a deterministic tar file for the specified file path, returning
+# the SHA for the tar file content
+# Any etc files in the $WORKSPACE (root) directory override the etc
+# files in the image dir, as long as it's a file also found in the
+# builders etc directory
+# the TARFILE and SHAFILE args must be paths located in /tmp
+function _tar_for_dir() {
+  local -r FILE_TAR="$1"
+  local -r FILE_SHA="$2"
+  local -r FILEPATH="$3"
+  local -r TMP_IMAGE_DIR="$(mktemp --tmpdir="${WORKSPACE}" --directory)"
+
+  WS_FILE_TAR="$(realpath "${FILE_TAR}" --relative-to="${WORKSPACE}")"
+  WS_FILE_SHA="$(realpath "${FILE_SHA}" --relative-to="${WORKSPACE}")"
+  WS_FILEPATH="$(realpath "${FILEPATH}" --relative-to="${WORKSPACE}")"
+  WS_TMP_IMAGE_DIR="$(realpath "${TMP_IMAGE_DIR}" --relative-to="${WORKSPACE}")"
+  # find workspace etc files that are also in the image dir and the builders etc dir
+  WORKSPACE_ETC_FILES="$({
+    # shellcheck disable=SC2012
+    ls -A -1 "${FILEPATH}" "${ETC_DIR}" | sort | uniq -d
+    ls -A -1 "${WORKSPACE}"
+  } | sort | uniq -d)"
+  # create a deterministic tarball of the collected files
+  docker run --rm \
+    --entrypoint=/bin/sh \
+    --volume "${WORKSPACE_MOUNT}":/workspace \
+    --workdir /workspace \
+    "${TAR_IMAGE}" -c "
+tar --create --dereference --directory='${WS_FILEPATH}' --exclude=test . | tar --extract --overwrite --directory='${WS_TMP_IMAGE_DIR}'
+
+# overwrite etc files in the image with the WORKSPACE's etc files
+if [ -n '${WORKSPACE_ETC_FILES}' ]; then
+  tar --create --dereference --exclude=test ${WORKSPACE_ETC_FILES} | tar --extract --overwrite --directory='${WS_TMP_IMAGE_DIR}'
+fi
+
+tar --create --dereference --sort=name --owner=0 --group=0 --numeric-owner --format=gnu --directory='${WS_TMP_IMAGE_DIR}' --file='${WS_FILE_TAR}' .
+TARLEN=\$(wc -c <'${WS_FILE_TAR}')
+{ printf 'blob %d\0' \${TARLEN}; tar --extract --file='${WS_FILE_TAR}' --to-stdout; } | sha256sum | cut -f1 -d' ' >'${WS_FILE_SHA}'
+"
+  rm -rf "${TMP_IMAGE_DIR}"
 }
 
-# try to create a deterministic tar file
-tar --create --dereference --sort=name --owner=0 --group=0 --numeric-owner --mtime='2022-07-01 12:00Z' --format=gnu --directory="${DIR_FULL}" --file="${TEMPTAR}" --exclude=test .
+TEMPTAR=$(mktemp --tmpdir="${WORKSPACE}" --dry-run).tar.gz
+readonly TEMPTAR
+SHAFILE=$(mktemp --tmpdir="${WORKSPACE}" --dry-run).sha
+readonly SHAFILE
 # use the tarfile size and file content to generate a sha256 hash
-SHA=$({ echo -ne "blob $(wc -c < "${TEMPTAR}")\0"; tar --extract --file="${TEMPTAR}" --to-stdout; } | sha256sum | cut -f1 -d" ")
-ARCH="$("${SCRIPT_DIR}"/get-architecture)"
+_tar_for_dir "${TEMPTAR}" "${SHAFILE}" "${IMAGE_PATH_FULL}"
+SHA=$(cat "${SHAFILE}")
+ARCH="$("${TOOLS_DIR}"/get-architecture)"
 readonly ARCH
 readonly IMAGE_TAG="${ARCH}-${SHA}"
-if [[ ${VERBOSE} -eq 1 ]]; then
-  printf "tag for docker inputs: %s\n" "${IMAGE_TAG}" &>/dev/stderr
-fi
 readonly IMAGE_TAGGED="${IMAGE_NAME}:${IMAGE_TAG}"
+# generate output
 printf "%s\n" "${IMAGE_TAGGED}"
 
 if [[ ${BUILD_IMAGE_IF_NEEDED} -eq 1 ]]; then
@@ -138,6 +194,6 @@ if [[ ${BUILD_IMAGE_IF_NEEDED} -eq 1 ]]; then
   # build container image and load it into the local docker client
   if ! docker image inspect "${IMAGE_TAGGED}" &>/dev/null; then
     printf "generating docker image %s\n" "${IMAGE_TAGGED}" &>/dev/stderr
-    docker build --tag "${IMAGE_TAGGED}" - <"${TEMPTAR}" &>/dev/stderr
+    docker buildx build ${DOCKER_BUILD_ARGS} --output=type=docker --tag "${IMAGE_TAGGED}" - <"${TEMPTAR}" &>/dev/stderr
   fi
 fi
